// Code generated by Fern. DO NOT EDIT.

package payouts

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/whopio/whopsdk-go/internal"
	big "math/big"
	time "time"
)

var (
	listSupportedMethodsRequestFieldAccountID               = big.NewInt(1 << 0)
	listSupportedMethodsRequestFieldUserID                  = big.NewInt(1 << 1)
	listSupportedMethodsRequestFieldCountry                 = big.NewInt(1 << 2)
	listSupportedMethodsRequestFieldAmount                  = big.NewInt(1 << 3)
	listSupportedMethodsRequestFieldCurrency                = big.NewInt(1 << 4)
	listSupportedMethodsRequestFieldSupportedPayoutMethodID = big.NewInt(1 << 5)
	listSupportedMethodsRequestFieldDestinationCurrency     = big.NewInt(1 << 6)
	listSupportedMethodsRequestFieldFirst                   = big.NewInt(1 << 7)
	listSupportedMethodsRequestFieldAfter                   = big.NewInt(1 << 8)
	listSupportedMethodsRequestFieldLast                    = big.NewInt(1 << 9)
	listSupportedMethodsRequestFieldBefore                  = big.NewInt(1 << 10)
)

type ListSupportedMethodsRequest struct {
	// The owning account ID (a biz_ identifier). Provide this or user_id.
	AccountID *string `json:"-" url:"account_id,omitempty"`
	// The owning user ID (a user_ identifier). Provide this or account_id.
	UserID *string `json:"-" url:"user_id,omitempty"`
	// ISO 3166-1 alpha-2 country code for the bank account or wallet, such as `US`. Defaults to the country of supported_payout_method_id when one is given, otherwise the payout account's country.
	Country *string `json:"-" url:"country,omitempty"`
	// Optional withdrawal amount in whole currency units, for example `250.00`. When provided, each destination includes per-currency fee and delivery quotes.
	Amount *float64 `json:"-" url:"amount,omitempty"`
	// Currency code of the amount, for example `usd`. Only meaningful with amount.
	Currency *string `json:"-" url:"currency,omitempty"`
	// Narrows the list to one supported payout method (a podst_ identifier) and includes the required_fields needed to save it as a payout method.
	SupportedPayoutMethodID *string `json:"-" url:"supported_payout_method_id,omitempty"`
	// Currency the supported payout method would deliver payouts in. Only meaningful with supported_payout_method_id; required fields vary by destination currency.
	DestinationCurrency *string `json:"-" url:"destination_currency,omitempty"`
	// Number of supported payout methods to return from the start of the window.
	First *int `json:"-" url:"first,omitempty"`
	// Cursor to fetch the page after (from page_info.end_cursor).
	After *string `json:"-" url:"after,omitempty"`
	// Number of supported payout methods to return from the end of the window.
	Last *int `json:"-" url:"last,omitempty"`
	// Cursor to fetch the page before (from page_info.start_cursor).
	Before *string `json:"-" url:"before,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListSupportedMethodsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsRequest) SetAccountID(accountID *string) {
	l.AccountID = accountID
	l.require(listSupportedMethodsRequestFieldAccountID)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsRequest) SetUserID(userID *string) {
	l.UserID = userID
	l.require(listSupportedMethodsRequestFieldUserID)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsRequest) SetCountry(country *string) {
	l.Country = country
	l.require(listSupportedMethodsRequestFieldCountry)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsRequest) SetAmount(amount *float64) {
	l.Amount = amount
	l.require(listSupportedMethodsRequestFieldAmount)
}

// SetCurrency sets the Currency field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsRequest) SetCurrency(currency *string) {
	l.Currency = currency
	l.require(listSupportedMethodsRequestFieldCurrency)
}

// SetSupportedPayoutMethodID sets the SupportedPayoutMethodID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsRequest) SetSupportedPayoutMethodID(supportedPayoutMethodID *string) {
	l.SupportedPayoutMethodID = supportedPayoutMethodID
	l.require(listSupportedMethodsRequestFieldSupportedPayoutMethodID)
}

// SetDestinationCurrency sets the DestinationCurrency field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsRequest) SetDestinationCurrency(destinationCurrency *string) {
	l.DestinationCurrency = destinationCurrency
	l.require(listSupportedMethodsRequestFieldDestinationCurrency)
}

// SetFirst sets the First field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsRequest) SetFirst(first *int) {
	l.First = first
	l.require(listSupportedMethodsRequestFieldFirst)
}

// SetAfter sets the After field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsRequest) SetAfter(after *string) {
	l.After = after
	l.require(listSupportedMethodsRequestFieldAfter)
}

// SetLast sets the Last field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsRequest) SetLast(last *int) {
	l.Last = last
	l.require(listSupportedMethodsRequestFieldLast)
}

// SetBefore sets the Before field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsRequest) SetBefore(before *string) {
	l.Before = before
	l.require(listSupportedMethodsRequestFieldBefore)
}

var (
	listSupportedMethodsResponseFieldData     = big.NewInt(1 << 0)
	listSupportedMethodsResponseFieldPageInfo = big.NewInt(1 << 1)
)

type ListSupportedMethodsResponse struct {
	Data     []*ListSupportedMethodsResponseDataItem `json:"data" url:"data"`
	PageInfo *ListSupportedMethodsResponsePageInfo   `json:"page_info" url:"page_info"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListSupportedMethodsResponse) GetData() []*ListSupportedMethodsResponseDataItem {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListSupportedMethodsResponse) GetPageInfo() *ListSupportedMethodsResponsePageInfo {
	if l == nil {
		return nil
	}
	return l.PageInfo
}

func (l *ListSupportedMethodsResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListSupportedMethodsResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponse) SetData(data []*ListSupportedMethodsResponseDataItem) {
	l.Data = data
	l.require(listSupportedMethodsResponseFieldData)
}

// SetPageInfo sets the PageInfo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponse) SetPageInfo(pageInfo *ListSupportedMethodsResponsePageInfo) {
	l.PageInfo = pageInfo
	l.require(listSupportedMethodsResponseFieldPageInfo)
}

func (l *ListSupportedMethodsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListSupportedMethodsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListSupportedMethodsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListSupportedMethodsResponse) MarshalJSON() ([]byte, error) {
	type embed ListSupportedMethodsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListSupportedMethodsResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	listSupportedMethodsResponseDataItemFieldDeliveryType             = big.NewInt(1 << 0)
	listSupportedMethodsResponseDataItemFieldIconURL                  = big.NewInt(1 << 1)
	listSupportedMethodsResponseDataItemFieldID                       = big.NewInt(1 << 2)
	listSupportedMethodsResponseDataItemFieldName                     = big.NewInt(1 << 3)
	listSupportedMethodsResponseDataItemFieldObject                   = big.NewInt(1 << 4)
	listSupportedMethodsResponseDataItemFieldQuotes                   = big.NewInt(1 << 5)
	listSupportedMethodsResponseDataItemFieldRequiredFields           = big.NewInt(1 << 6)
	listSupportedMethodsResponseDataItemFieldSupportsInstantDelivery  = big.NewInt(1 << 7)
	listSupportedMethodsResponseDataItemFieldSupportsStandardDelivery = big.NewInt(1 << 8)
)

type ListSupportedMethodsResponseDataItem struct {
	// How funds are delivered, for example `bank_deposit`.
	DeliveryType ListSupportedMethodsResponseDataItemDeliveryType `json:"delivery_type" url:"delivery_type"`
	// Supported payout method icon URL.
	IconURL *string `json:"icon_url,omitempty" url:"icon_url,omitempty"`
	// Supported payout method ID.
	ID string `json:"id" url:"id"`
	// Supported payout method display name.
	Name   *string                                    `json:"name,omitempty" url:"name,omitempty"`
	Object ListSupportedMethodsResponseDataItemObject `json:"object" url:"object"`
	// Fee and delivery estimates for the requested amount, one per destination currency. Null unless an amount was provided.
	Quotes []*ListSupportedMethodsResponseDataItemQuotesItem `json:"quotes,omitempty" url:"quotes,omitempty"`
	// Fields to collect before saving this supported payout method. Present only when supported_payout_method_id narrows the request to one method.
	RequiredFields           []*ListSupportedMethodsResponseDataItemRequiredFieldsItem `json:"required_fields,omitempty" url:"required_fields,omitempty"`
	SupportsInstantDelivery  bool                                                      `json:"supports_instant_delivery" url:"supports_instant_delivery"`
	SupportsStandardDelivery bool                                                      `json:"supports_standard_delivery" url:"supports_standard_delivery"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListSupportedMethodsResponseDataItem) GetDeliveryType() ListSupportedMethodsResponseDataItemDeliveryType {
	if l == nil {
		return ""
	}
	return l.DeliveryType
}

func (l *ListSupportedMethodsResponseDataItem) GetIconURL() *string {
	if l == nil {
		return nil
	}
	return l.IconURL
}

func (l *ListSupportedMethodsResponseDataItem) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListSupportedMethodsResponseDataItem) GetName() *string {
	if l == nil {
		return nil
	}
	return l.Name
}

func (l *ListSupportedMethodsResponseDataItem) GetObject() ListSupportedMethodsResponseDataItemObject {
	if l == nil {
		return ""
	}
	return l.Object
}

func (l *ListSupportedMethodsResponseDataItem) GetQuotes() []*ListSupportedMethodsResponseDataItemQuotesItem {
	if l == nil {
		return nil
	}
	return l.Quotes
}

func (l *ListSupportedMethodsResponseDataItem) GetRequiredFields() []*ListSupportedMethodsResponseDataItemRequiredFieldsItem {
	if l == nil {
		return nil
	}
	return l.RequiredFields
}

func (l *ListSupportedMethodsResponseDataItem) GetSupportsInstantDelivery() bool {
	if l == nil {
		return false
	}
	return l.SupportsInstantDelivery
}

func (l *ListSupportedMethodsResponseDataItem) GetSupportsStandardDelivery() bool {
	if l == nil {
		return false
	}
	return l.SupportsStandardDelivery
}

func (l *ListSupportedMethodsResponseDataItem) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListSupportedMethodsResponseDataItem) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetDeliveryType sets the DeliveryType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponseDataItem) SetDeliveryType(deliveryType ListSupportedMethodsResponseDataItemDeliveryType) {
	l.DeliveryType = deliveryType
	l.require(listSupportedMethodsResponseDataItemFieldDeliveryType)
}

// SetIconURL sets the IconURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponseDataItem) SetIconURL(iconURL *string) {
	l.IconURL = iconURL
	l.require(listSupportedMethodsResponseDataItemFieldIconURL)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponseDataItem) SetID(id string) {
	l.ID = id
	l.require(listSupportedMethodsResponseDataItemFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponseDataItem) SetName(name *string) {
	l.Name = name
	l.require(listSupportedMethodsResponseDataItemFieldName)
}

// SetObject sets the Object field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponseDataItem) SetObject(object ListSupportedMethodsResponseDataItemObject) {
	l.Object = object
	l.require(listSupportedMethodsResponseDataItemFieldObject)
}

// SetQuotes sets the Quotes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponseDataItem) SetQuotes(quotes []*ListSupportedMethodsResponseDataItemQuotesItem) {
	l.Quotes = quotes
	l.require(listSupportedMethodsResponseDataItemFieldQuotes)
}

// SetRequiredFields sets the RequiredFields field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponseDataItem) SetRequiredFields(requiredFields []*ListSupportedMethodsResponseDataItemRequiredFieldsItem) {
	l.RequiredFields = requiredFields
	l.require(listSupportedMethodsResponseDataItemFieldRequiredFields)
}

// SetSupportsInstantDelivery sets the SupportsInstantDelivery field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponseDataItem) SetSupportsInstantDelivery(supportsInstantDelivery bool) {
	l.SupportsInstantDelivery = supportsInstantDelivery
	l.require(listSupportedMethodsResponseDataItemFieldSupportsInstantDelivery)
}

// SetSupportsStandardDelivery sets the SupportsStandardDelivery field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponseDataItem) SetSupportsStandardDelivery(supportsStandardDelivery bool) {
	l.SupportsStandardDelivery = supportsStandardDelivery
	l.require(listSupportedMethodsResponseDataItemFieldSupportsStandardDelivery)
}

func (l *ListSupportedMethodsResponseDataItem) UnmarshalJSON(data []byte) error {
	type unmarshaler ListSupportedMethodsResponseDataItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListSupportedMethodsResponseDataItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListSupportedMethodsResponseDataItem) MarshalJSON() ([]byte, error) {
	type embed ListSupportedMethodsResponseDataItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListSupportedMethodsResponseDataItem) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

// How funds are delivered, for example `bank_deposit`.
type ListSupportedMethodsResponseDataItemDeliveryType string

const (
	ListSupportedMethodsResponseDataItemDeliveryTypeCashPickup     ListSupportedMethodsResponseDataItemDeliveryType = "cash_pickup"
	ListSupportedMethodsResponseDataItemDeliveryTypeBankDeposit    ListSupportedMethodsResponseDataItemDeliveryType = "bank_deposit"
	ListSupportedMethodsResponseDataItemDeliveryTypeHomeDelivery   ListSupportedMethodsResponseDataItemDeliveryType = "home_delivery"
	ListSupportedMethodsResponseDataItemDeliveryTypeMobileWallet   ListSupportedMethodsResponseDataItemDeliveryType = "mobile_wallet"
	ListSupportedMethodsResponseDataItemDeliveryTypeMasspayCard    ListSupportedMethodsResponseDataItemDeliveryType = "masspay_card"
	ListSupportedMethodsResponseDataItemDeliveryTypePaperCheck     ListSupportedMethodsResponseDataItemDeliveryType = "paper_check"
	ListSupportedMethodsResponseDataItemDeliveryTypeBill           ListSupportedMethodsResponseDataItemDeliveryType = "bill"
	ListSupportedMethodsResponseDataItemDeliveryTypeCryptocurrency ListSupportedMethodsResponseDataItemDeliveryType = "cryptocurrency"
	ListSupportedMethodsResponseDataItemDeliveryTypeUnknown        ListSupportedMethodsResponseDataItemDeliveryType = "unknown"
)

func NewListSupportedMethodsResponseDataItemDeliveryTypeFromString(s string) (ListSupportedMethodsResponseDataItemDeliveryType, error) {
	switch s {
	case "cash_pickup":
		return ListSupportedMethodsResponseDataItemDeliveryTypeCashPickup, nil
	case "bank_deposit":
		return ListSupportedMethodsResponseDataItemDeliveryTypeBankDeposit, nil
	case "home_delivery":
		return ListSupportedMethodsResponseDataItemDeliveryTypeHomeDelivery, nil
	case "mobile_wallet":
		return ListSupportedMethodsResponseDataItemDeliveryTypeMobileWallet, nil
	case "masspay_card":
		return ListSupportedMethodsResponseDataItemDeliveryTypeMasspayCard, nil
	case "paper_check":
		return ListSupportedMethodsResponseDataItemDeliveryTypePaperCheck, nil
	case "bill":
		return ListSupportedMethodsResponseDataItemDeliveryTypeBill, nil
	case "cryptocurrency":
		return ListSupportedMethodsResponseDataItemDeliveryTypeCryptocurrency, nil
	case "unknown":
		return ListSupportedMethodsResponseDataItemDeliveryTypeUnknown, nil
	}
	var t ListSupportedMethodsResponseDataItemDeliveryType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l ListSupportedMethodsResponseDataItemDeliveryType) Ptr() *ListSupportedMethodsResponseDataItemDeliveryType {
	return &l
}

type ListSupportedMethodsResponseDataItemObject string

const (
	ListSupportedMethodsResponseDataItemObjectSupportedPayoutMethod ListSupportedMethodsResponseDataItemObject = "supported_payout_method"
)

func NewListSupportedMethodsResponseDataItemObjectFromString(s string) (ListSupportedMethodsResponseDataItemObject, error) {
	switch s {
	case "supported_payout_method":
		return ListSupportedMethodsResponseDataItemObjectSupportedPayoutMethod, nil
	}
	var t ListSupportedMethodsResponseDataItemObject
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l ListSupportedMethodsResponseDataItemObject) Ptr() *ListSupportedMethodsResponseDataItemObject {
	return &l
}

var (
	listSupportedMethodsResponseDataItemQuotesItemFieldAmount              = big.NewInt(1 << 0)
	listSupportedMethodsResponseDataItemQuotesItemFieldCurrency            = big.NewInt(1 << 1)
	listSupportedMethodsResponseDataItemQuotesItemFieldDestinationCurrency = big.NewInt(1 << 2)
	listSupportedMethodsResponseDataItemQuotesItemFieldExchangeRate        = big.NewInt(1 << 3)
	listSupportedMethodsResponseDataItemQuotesItemFieldInstant             = big.NewInt(1 << 4)
	listSupportedMethodsResponseDataItemQuotesItemFieldMaxLimit            = big.NewInt(1 << 5)
	listSupportedMethodsResponseDataItemQuotesItemFieldMinLimit            = big.NewInt(1 << 6)
	listSupportedMethodsResponseDataItemQuotesItemFieldStandard            = big.NewInt(1 << 7)
)

type ListSupportedMethodsResponseDataItemQuotesItem struct {
	// The withdrawal amount the quote is for.
	Amount float64 `json:"amount" url:"amount"`
	// Currency of the quoted amount.
	Currency string `json:"currency" url:"currency"`
	// Currency the funds are delivered in.
	DestinationCurrency string `json:"destination_currency" url:"destination_currency"`
	// Exchange rate from the withdrawal currency to the destination currency.
	ExchangeRate float64 `json:"exchange_rate" url:"exchange_rate"`
	// Instant-delivery estimate. Null if unsupported, unavailable for the account, or the amount does not cover the fee.
	Instant *ListSupportedMethodsResponseDataItemQuotesItemInstant `json:"instant,omitempty" url:"instant,omitempty"`
	// Maximum withdrawal amount, in the withdrawal currency.
	MaxLimit *float64 `json:"max_limit,omitempty" url:"max_limit,omitempty"`
	// Minimum withdrawal amount, in the withdrawal currency.
	MinLimit float64 `json:"min_limit" url:"min_limit"`
	// Standard-delivery estimate. Null if unsupported or the amount does not cover the fee.
	Standard *ListSupportedMethodsResponseDataItemQuotesItemStandard `json:"standard,omitempty" url:"standard,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListSupportedMethodsResponseDataItemQuotesItem) GetAmount() float64 {
	if l == nil {
		return 0
	}
	return l.Amount
}

func (l *ListSupportedMethodsResponseDataItemQuotesItem) GetCurrency() string {
	if l == nil {
		return ""
	}
	return l.Currency
}

func (l *ListSupportedMethodsResponseDataItemQuotesItem) GetDestinationCurrency() string {
	if l == nil {
		return ""
	}
	return l.DestinationCurrency
}

func (l *ListSupportedMethodsResponseDataItemQuotesItem) GetExchangeRate() float64 {
	if l == nil {
		return 0
	}
	return l.ExchangeRate
}

func (l *ListSupportedMethodsResponseDataItemQuotesItem) GetInstant() *ListSupportedMethodsResponseDataItemQuotesItemInstant {
	if l == nil {
		return nil
	}
	return l.Instant
}

func (l *ListSupportedMethodsResponseDataItemQuotesItem) GetMaxLimit() *float64 {
	if l == nil {
		return nil
	}
	return l.MaxLimit
}

func (l *ListSupportedMethodsResponseDataItemQuotesItem) GetMinLimit() float64 {
	if l == nil {
		return 0
	}
	return l.MinLimit
}

func (l *ListSupportedMethodsResponseDataItemQuotesItem) GetStandard() *ListSupportedMethodsResponseDataItemQuotesItemStandard {
	if l == nil {
		return nil
	}
	return l.Standard
}

func (l *ListSupportedMethodsResponseDataItemQuotesItem) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListSupportedMethodsResponseDataItemQuotesItem) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponseDataItemQuotesItem) SetAmount(amount float64) {
	l.Amount = amount
	l.require(listSupportedMethodsResponseDataItemQuotesItemFieldAmount)
}

// SetCurrency sets the Currency field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponseDataItemQuotesItem) SetCurrency(currency string) {
	l.Currency = currency
	l.require(listSupportedMethodsResponseDataItemQuotesItemFieldCurrency)
}

// SetDestinationCurrency sets the DestinationCurrency field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponseDataItemQuotesItem) SetDestinationCurrency(destinationCurrency string) {
	l.DestinationCurrency = destinationCurrency
	l.require(listSupportedMethodsResponseDataItemQuotesItemFieldDestinationCurrency)
}

// SetExchangeRate sets the ExchangeRate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponseDataItemQuotesItem) SetExchangeRate(exchangeRate float64) {
	l.ExchangeRate = exchangeRate
	l.require(listSupportedMethodsResponseDataItemQuotesItemFieldExchangeRate)
}

// SetInstant sets the Instant field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponseDataItemQuotesItem) SetInstant(instant *ListSupportedMethodsResponseDataItemQuotesItemInstant) {
	l.Instant = instant
	l.require(listSupportedMethodsResponseDataItemQuotesItemFieldInstant)
}

// SetMaxLimit sets the MaxLimit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponseDataItemQuotesItem) SetMaxLimit(maxLimit *float64) {
	l.MaxLimit = maxLimit
	l.require(listSupportedMethodsResponseDataItemQuotesItemFieldMaxLimit)
}

// SetMinLimit sets the MinLimit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponseDataItemQuotesItem) SetMinLimit(minLimit float64) {
	l.MinLimit = minLimit
	l.require(listSupportedMethodsResponseDataItemQuotesItemFieldMinLimit)
}

// SetStandard sets the Standard field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponseDataItemQuotesItem) SetStandard(standard *ListSupportedMethodsResponseDataItemQuotesItemStandard) {
	l.Standard = standard
	l.require(listSupportedMethodsResponseDataItemQuotesItemFieldStandard)
}

func (l *ListSupportedMethodsResponseDataItemQuotesItem) UnmarshalJSON(data []byte) error {
	type unmarshaler ListSupportedMethodsResponseDataItemQuotesItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListSupportedMethodsResponseDataItemQuotesItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListSupportedMethodsResponseDataItemQuotesItem) MarshalJSON() ([]byte, error) {
	type embed ListSupportedMethodsResponseDataItemQuotesItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListSupportedMethodsResponseDataItemQuotesItem) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

// Instant-delivery estimate. Null if unsupported, unavailable for the account, or the amount does not cover the fee.
var (
	listSupportedMethodsResponseDataItemQuotesItemInstantFieldEstimatedArrival = big.NewInt(1 << 0)
	listSupportedMethodsResponseDataItemQuotesItemInstantFieldFee              = big.NewInt(1 << 1)
	listSupportedMethodsResponseDataItemQuotesItemInstantFieldTotalReceived    = big.NewInt(1 << 2)
)

type ListSupportedMethodsResponseDataItemQuotesItemInstant struct {
	EstimatedArrival time.Time `json:"estimated_arrival" url:"estimated_arrival"`
	Fee              float64   `json:"fee" url:"fee"`
	TotalReceived    float64   `json:"total_received" url:"total_received"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListSupportedMethodsResponseDataItemQuotesItemInstant) GetEstimatedArrival() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.EstimatedArrival
}

func (l *ListSupportedMethodsResponseDataItemQuotesItemInstant) GetFee() float64 {
	if l == nil {
		return 0
	}
	return l.Fee
}

func (l *ListSupportedMethodsResponseDataItemQuotesItemInstant) GetTotalReceived() float64 {
	if l == nil {
		return 0
	}
	return l.TotalReceived
}

func (l *ListSupportedMethodsResponseDataItemQuotesItemInstant) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListSupportedMethodsResponseDataItemQuotesItemInstant) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetEstimatedArrival sets the EstimatedArrival field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponseDataItemQuotesItemInstant) SetEstimatedArrival(estimatedArrival time.Time) {
	l.EstimatedArrival = estimatedArrival
	l.require(listSupportedMethodsResponseDataItemQuotesItemInstantFieldEstimatedArrival)
}

// SetFee sets the Fee field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponseDataItemQuotesItemInstant) SetFee(fee float64) {
	l.Fee = fee
	l.require(listSupportedMethodsResponseDataItemQuotesItemInstantFieldFee)
}

// SetTotalReceived sets the TotalReceived field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponseDataItemQuotesItemInstant) SetTotalReceived(totalReceived float64) {
	l.TotalReceived = totalReceived
	l.require(listSupportedMethodsResponseDataItemQuotesItemInstantFieldTotalReceived)
}

func (l *ListSupportedMethodsResponseDataItemQuotesItemInstant) UnmarshalJSON(data []byte) error {
	type embed ListSupportedMethodsResponseDataItemQuotesItemInstant
	var unmarshaler = struct {
		embed
		EstimatedArrival *internal.DateTime `json:"estimated_arrival"`
	}{
		embed: embed(*l),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*l = ListSupportedMethodsResponseDataItemQuotesItemInstant(unmarshaler.embed)
	l.EstimatedArrival = unmarshaler.EstimatedArrival.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListSupportedMethodsResponseDataItemQuotesItemInstant) MarshalJSON() ([]byte, error) {
	type embed ListSupportedMethodsResponseDataItemQuotesItemInstant
	var marshaler = struct {
		embed
		EstimatedArrival *internal.DateTime `json:"estimated_arrival"`
	}{
		embed:            embed(*l),
		EstimatedArrival: internal.NewDateTime(l.EstimatedArrival),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListSupportedMethodsResponseDataItemQuotesItemInstant) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

// Standard-delivery estimate. Null if unsupported or the amount does not cover the fee.
var (
	listSupportedMethodsResponseDataItemQuotesItemStandardFieldEstimatedArrival = big.NewInt(1 << 0)
	listSupportedMethodsResponseDataItemQuotesItemStandardFieldFee              = big.NewInt(1 << 1)
	listSupportedMethodsResponseDataItemQuotesItemStandardFieldTotalReceived    = big.NewInt(1 << 2)
)

type ListSupportedMethodsResponseDataItemQuotesItemStandard struct {
	EstimatedArrival time.Time `json:"estimated_arrival" url:"estimated_arrival"`
	Fee              float64   `json:"fee" url:"fee"`
	TotalReceived    float64   `json:"total_received" url:"total_received"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListSupportedMethodsResponseDataItemQuotesItemStandard) GetEstimatedArrival() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.EstimatedArrival
}

func (l *ListSupportedMethodsResponseDataItemQuotesItemStandard) GetFee() float64 {
	if l == nil {
		return 0
	}
	return l.Fee
}

func (l *ListSupportedMethodsResponseDataItemQuotesItemStandard) GetTotalReceived() float64 {
	if l == nil {
		return 0
	}
	return l.TotalReceived
}

func (l *ListSupportedMethodsResponseDataItemQuotesItemStandard) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListSupportedMethodsResponseDataItemQuotesItemStandard) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetEstimatedArrival sets the EstimatedArrival field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponseDataItemQuotesItemStandard) SetEstimatedArrival(estimatedArrival time.Time) {
	l.EstimatedArrival = estimatedArrival
	l.require(listSupportedMethodsResponseDataItemQuotesItemStandardFieldEstimatedArrival)
}

// SetFee sets the Fee field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponseDataItemQuotesItemStandard) SetFee(fee float64) {
	l.Fee = fee
	l.require(listSupportedMethodsResponseDataItemQuotesItemStandardFieldFee)
}

// SetTotalReceived sets the TotalReceived field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponseDataItemQuotesItemStandard) SetTotalReceived(totalReceived float64) {
	l.TotalReceived = totalReceived
	l.require(listSupportedMethodsResponseDataItemQuotesItemStandardFieldTotalReceived)
}

func (l *ListSupportedMethodsResponseDataItemQuotesItemStandard) UnmarshalJSON(data []byte) error {
	type embed ListSupportedMethodsResponseDataItemQuotesItemStandard
	var unmarshaler = struct {
		embed
		EstimatedArrival *internal.DateTime `json:"estimated_arrival"`
	}{
		embed: embed(*l),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*l = ListSupportedMethodsResponseDataItemQuotesItemStandard(unmarshaler.embed)
	l.EstimatedArrival = unmarshaler.EstimatedArrival.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListSupportedMethodsResponseDataItemQuotesItemStandard) MarshalJSON() ([]byte, error) {
	type embed ListSupportedMethodsResponseDataItemQuotesItemStandard
	var marshaler = struct {
		embed
		EstimatedArrival *internal.DateTime `json:"estimated_arrival"`
	}{
		embed:            embed(*l),
		EstimatedArrival: internal.NewDateTime(l.EstimatedArrival),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListSupportedMethodsResponseDataItemQuotesItemStandard) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	listSupportedMethodsResponseDataItemRequiredFieldsItemFieldID          = big.NewInt(1 << 0)
	listSupportedMethodsResponseDataItemRequiredFieldsItemFieldInputType   = big.NewInt(1 << 1)
	listSupportedMethodsResponseDataItemRequiredFieldsItemFieldLabel       = big.NewInt(1 << 2)
	listSupportedMethodsResponseDataItemRequiredFieldsItemFieldObject      = big.NewInt(1 << 3)
	listSupportedMethodsResponseDataItemRequiredFieldsItemFieldOptions     = big.NewInt(1 << 4)
	listSupportedMethodsResponseDataItemRequiredFieldsItemFieldPlaceholder = big.NewInt(1 << 5)
	listSupportedMethodsResponseDataItemRequiredFieldsItemFieldRequired    = big.NewInt(1 << 6)
	listSupportedMethodsResponseDataItemRequiredFieldsItemFieldSensitive   = big.NewInt(1 << 7)
	listSupportedMethodsResponseDataItemRequiredFieldsItemFieldType        = big.NewInt(1 << 8)
	listSupportedMethodsResponseDataItemRequiredFieldsItemFieldValidation  = big.NewInt(1 << 9)
)

type ListSupportedMethodsResponseDataItemRequiredFieldsItem struct {
	// Stable field ID (`fld_` + the semantic type), used as the field key when creating the payout method. Safe to hardcode — it never changes for a given field.
	ID string `json:"id" url:"id"`
	// How to collect the value: `text`, `options`, or `date`.
	InputType string `json:"input_type" url:"input_type"`
	// Human-readable field name.
	Label  string                                                       `json:"label" url:"label"`
	Object ListSupportedMethodsResponseDataItemRequiredFieldsItemObject `json:"object" url:"object"`
	// Allowed values for options fields.
	Options []string `json:"options,omitempty" url:"options,omitempty"`
	// Example value.
	Placeholder *string `json:"placeholder,omitempty" url:"placeholder,omitempty"`
	// Whether the field must be provided.
	Required bool `json:"required" url:"required"`
	// Whether the value is vaulted in transit and never stored raw.
	Sensitive bool `json:"sensitive" url:"sensitive"`
	// Semantic field type, for example `bank_account_number` or `swift`.
	Type string `json:"type" url:"type"`
	// Regex the value must match. Null for options fields.
	Validation *string `json:"validation,omitempty" url:"validation,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListSupportedMethodsResponseDataItemRequiredFieldsItem) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListSupportedMethodsResponseDataItemRequiredFieldsItem) GetInputType() string {
	if l == nil {
		return ""
	}
	return l.InputType
}

func (l *ListSupportedMethodsResponseDataItemRequiredFieldsItem) GetLabel() string {
	if l == nil {
		return ""
	}
	return l.Label
}

func (l *ListSupportedMethodsResponseDataItemRequiredFieldsItem) GetObject() ListSupportedMethodsResponseDataItemRequiredFieldsItemObject {
	if l == nil {
		return ""
	}
	return l.Object
}

func (l *ListSupportedMethodsResponseDataItemRequiredFieldsItem) GetOptions() []string {
	if l == nil {
		return nil
	}
	return l.Options
}

func (l *ListSupportedMethodsResponseDataItemRequiredFieldsItem) GetPlaceholder() *string {
	if l == nil {
		return nil
	}
	return l.Placeholder
}

func (l *ListSupportedMethodsResponseDataItemRequiredFieldsItem) GetRequired() bool {
	if l == nil {
		return false
	}
	return l.Required
}

func (l *ListSupportedMethodsResponseDataItemRequiredFieldsItem) GetSensitive() bool {
	if l == nil {
		return false
	}
	return l.Sensitive
}

func (l *ListSupportedMethodsResponseDataItemRequiredFieldsItem) GetType() string {
	if l == nil {
		return ""
	}
	return l.Type
}

func (l *ListSupportedMethodsResponseDataItemRequiredFieldsItem) GetValidation() *string {
	if l == nil {
		return nil
	}
	return l.Validation
}

func (l *ListSupportedMethodsResponseDataItemRequiredFieldsItem) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListSupportedMethodsResponseDataItemRequiredFieldsItem) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponseDataItemRequiredFieldsItem) SetID(id string) {
	l.ID = id
	l.require(listSupportedMethodsResponseDataItemRequiredFieldsItemFieldID)
}

// SetInputType sets the InputType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponseDataItemRequiredFieldsItem) SetInputType(inputType string) {
	l.InputType = inputType
	l.require(listSupportedMethodsResponseDataItemRequiredFieldsItemFieldInputType)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponseDataItemRequiredFieldsItem) SetLabel(label string) {
	l.Label = label
	l.require(listSupportedMethodsResponseDataItemRequiredFieldsItemFieldLabel)
}

// SetObject sets the Object field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponseDataItemRequiredFieldsItem) SetObject(object ListSupportedMethodsResponseDataItemRequiredFieldsItemObject) {
	l.Object = object
	l.require(listSupportedMethodsResponseDataItemRequiredFieldsItemFieldObject)
}

// SetOptions sets the Options field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponseDataItemRequiredFieldsItem) SetOptions(options []string) {
	l.Options = options
	l.require(listSupportedMethodsResponseDataItemRequiredFieldsItemFieldOptions)
}

// SetPlaceholder sets the Placeholder field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponseDataItemRequiredFieldsItem) SetPlaceholder(placeholder *string) {
	l.Placeholder = placeholder
	l.require(listSupportedMethodsResponseDataItemRequiredFieldsItemFieldPlaceholder)
}

// SetRequired sets the Required field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponseDataItemRequiredFieldsItem) SetRequired(required bool) {
	l.Required = required
	l.require(listSupportedMethodsResponseDataItemRequiredFieldsItemFieldRequired)
}

// SetSensitive sets the Sensitive field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponseDataItemRequiredFieldsItem) SetSensitive(sensitive bool) {
	l.Sensitive = sensitive
	l.require(listSupportedMethodsResponseDataItemRequiredFieldsItemFieldSensitive)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponseDataItemRequiredFieldsItem) SetType(type_ string) {
	l.Type = type_
	l.require(listSupportedMethodsResponseDataItemRequiredFieldsItemFieldType)
}

// SetValidation sets the Validation field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponseDataItemRequiredFieldsItem) SetValidation(validation *string) {
	l.Validation = validation
	l.require(listSupportedMethodsResponseDataItemRequiredFieldsItemFieldValidation)
}

func (l *ListSupportedMethodsResponseDataItemRequiredFieldsItem) UnmarshalJSON(data []byte) error {
	type unmarshaler ListSupportedMethodsResponseDataItemRequiredFieldsItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListSupportedMethodsResponseDataItemRequiredFieldsItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListSupportedMethodsResponseDataItemRequiredFieldsItem) MarshalJSON() ([]byte, error) {
	type embed ListSupportedMethodsResponseDataItemRequiredFieldsItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListSupportedMethodsResponseDataItemRequiredFieldsItem) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

type ListSupportedMethodsResponseDataItemRequiredFieldsItemObject string

const (
	ListSupportedMethodsResponseDataItemRequiredFieldsItemObjectRequiredField ListSupportedMethodsResponseDataItemRequiredFieldsItemObject = "required_field"
)

func NewListSupportedMethodsResponseDataItemRequiredFieldsItemObjectFromString(s string) (ListSupportedMethodsResponseDataItemRequiredFieldsItemObject, error) {
	switch s {
	case "required_field":
		return ListSupportedMethodsResponseDataItemRequiredFieldsItemObjectRequiredField, nil
	}
	var t ListSupportedMethodsResponseDataItemRequiredFieldsItemObject
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l ListSupportedMethodsResponseDataItemRequiredFieldsItemObject) Ptr() *ListSupportedMethodsResponseDataItemRequiredFieldsItemObject {
	return &l
}

var (
	listSupportedMethodsResponsePageInfoFieldEndCursor       = big.NewInt(1 << 0)
	listSupportedMethodsResponsePageInfoFieldHasNextPage     = big.NewInt(1 << 1)
	listSupportedMethodsResponsePageInfoFieldHasPreviousPage = big.NewInt(1 << 2)
	listSupportedMethodsResponsePageInfoFieldStartCursor     = big.NewInt(1 << 3)
)

type ListSupportedMethodsResponsePageInfo struct {
	EndCursor       *string `json:"end_cursor,omitempty" url:"end_cursor,omitempty"`
	HasNextPage     bool    `json:"has_next_page" url:"has_next_page"`
	HasPreviousPage bool    `json:"has_previous_page" url:"has_previous_page"`
	StartCursor     *string `json:"start_cursor,omitempty" url:"start_cursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListSupportedMethodsResponsePageInfo) GetEndCursor() *string {
	if l == nil {
		return nil
	}
	return l.EndCursor
}

func (l *ListSupportedMethodsResponsePageInfo) GetHasNextPage() bool {
	if l == nil {
		return false
	}
	return l.HasNextPage
}

func (l *ListSupportedMethodsResponsePageInfo) GetHasPreviousPage() bool {
	if l == nil {
		return false
	}
	return l.HasPreviousPage
}

func (l *ListSupportedMethodsResponsePageInfo) GetStartCursor() *string {
	if l == nil {
		return nil
	}
	return l.StartCursor
}

func (l *ListSupportedMethodsResponsePageInfo) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListSupportedMethodsResponsePageInfo) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetEndCursor sets the EndCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponsePageInfo) SetEndCursor(endCursor *string) {
	l.EndCursor = endCursor
	l.require(listSupportedMethodsResponsePageInfoFieldEndCursor)
}

// SetHasNextPage sets the HasNextPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponsePageInfo) SetHasNextPage(hasNextPage bool) {
	l.HasNextPage = hasNextPage
	l.require(listSupportedMethodsResponsePageInfoFieldHasNextPage)
}

// SetHasPreviousPage sets the HasPreviousPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponsePageInfo) SetHasPreviousPage(hasPreviousPage bool) {
	l.HasPreviousPage = hasPreviousPage
	l.require(listSupportedMethodsResponsePageInfoFieldHasPreviousPage)
}

// SetStartCursor sets the StartCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSupportedMethodsResponsePageInfo) SetStartCursor(startCursor *string) {
	l.StartCursor = startCursor
	l.require(listSupportedMethodsResponsePageInfoFieldStartCursor)
}

func (l *ListSupportedMethodsResponsePageInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler ListSupportedMethodsResponsePageInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListSupportedMethodsResponsePageInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListSupportedMethodsResponsePageInfo) MarshalJSON() ([]byte, error) {
	type embed ListSupportedMethodsResponsePageInfo
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListSupportedMethodsResponsePageInfo) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}
