// Code generated by Fern. DO NOT EDIT.

package whopsdk

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/whopio/whopsdk-go/internal"
	big "math/big"
	time "time"
)

var (
	listIdentityProfileRequestFieldAfter       = big.NewInt(1 << 0)
	listIdentityProfileRequestFieldBefore      = big.NewInt(1 << 1)
	listIdentityProfileRequestFieldFirst       = big.NewInt(1 << 2)
	listIdentityProfileRequestFieldLast        = big.NewInt(1 << 3)
	listIdentityProfileRequestFieldProfileType = big.NewInt(1 << 4)
	listIdentityProfileRequestFieldStatus      = big.NewInt(1 << 5)
	listIdentityProfileRequestFieldAccountID   = big.NewInt(1 << 6)
)

type ListIdentityProfileRequest struct {
	// Returns the elements in the list that come after the specified cursor.
	After *string `json:"-" url:"after,omitempty"`
	// Returns the elements in the list that come before the specified cursor.
	Before *string `json:"-" url:"before,omitempty"`
	// Returns the first _n_ elements from the list.
	First *int `json:"-" url:"first,omitempty"`
	// Returns the last _n_ elements from the list.
	Last        *int                     `json:"-" url:"last,omitempty"`
	ProfileType *IdentityProfileKinds    `json:"-" url:"profile_type,omitempty"`
	Status      *IdentityProfileStatuses `json:"-" url:"status,omitempty"`
	// The unique identifier of the company to filter to. When omitted, returns IPs across all ledgers the actor can read.
	AccountID *string `json:"-" url:"account_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListIdentityProfileRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetAfter sets the After field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListIdentityProfileRequest) SetAfter(after *string) {
	l.After = after
	l.require(listIdentityProfileRequestFieldAfter)
}

// SetBefore sets the Before field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListIdentityProfileRequest) SetBefore(before *string) {
	l.Before = before
	l.require(listIdentityProfileRequestFieldBefore)
}

// SetFirst sets the First field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListIdentityProfileRequest) SetFirst(first *int) {
	l.First = first
	l.require(listIdentityProfileRequestFieldFirst)
}

// SetLast sets the Last field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListIdentityProfileRequest) SetLast(last *int) {
	l.Last = last
	l.require(listIdentityProfileRequestFieldLast)
}

// SetProfileType sets the ProfileType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListIdentityProfileRequest) SetProfileType(profileType *IdentityProfileKinds) {
	l.ProfileType = profileType
	l.require(listIdentityProfileRequestFieldProfileType)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListIdentityProfileRequest) SetStatus(status *IdentityProfileStatuses) {
	l.Status = status
	l.require(listIdentityProfileRequestFieldStatus)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListIdentityProfileRequest) SetAccountID(accountID *string) {
	l.AccountID = accountID
	l.require(listIdentityProfileRequestFieldAccountID)
}

var (
	listVerificationsIdentityProfileRequestFieldID     = big.NewInt(1 << 0)
	listVerificationsIdentityProfileRequestFieldAfter  = big.NewInt(1 << 1)
	listVerificationsIdentityProfileRequestFieldBefore = big.NewInt(1 << 2)
	listVerificationsIdentityProfileRequestFieldFirst  = big.NewInt(1 << 3)
	listVerificationsIdentityProfileRequestFieldLast   = big.NewInt(1 << 4)
)

type ListVerificationsIdentityProfileRequest struct {
	// The unique identifier of the identity profile (idpf_xxx).
	ID string `json:"-" url:"-"`
	// Returns the elements in the list that come after the specified cursor.
	After *string `json:"-" url:"after,omitempty"`
	// Returns the elements in the list that come before the specified cursor.
	Before *string `json:"-" url:"before,omitempty"`
	// Returns the first _n_ elements from the list.
	First *int `json:"-" url:"first,omitempty"`
	// Returns the last _n_ elements from the list.
	Last *int `json:"-" url:"last,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListVerificationsIdentityProfileRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListVerificationsIdentityProfileRequest) SetID(id string) {
	l.ID = id
	l.require(listVerificationsIdentityProfileRequestFieldID)
}

// SetAfter sets the After field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListVerificationsIdentityProfileRequest) SetAfter(after *string) {
	l.After = after
	l.require(listVerificationsIdentityProfileRequestFieldAfter)
}

// SetBefore sets the Before field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListVerificationsIdentityProfileRequest) SetBefore(before *string) {
	l.Before = before
	l.require(listVerificationsIdentityProfileRequestFieldBefore)
}

// SetFirst sets the First field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListVerificationsIdentityProfileRequest) SetFirst(first *int) {
	l.First = first
	l.require(listVerificationsIdentityProfileRequestFieldFirst)
}

// SetLast sets the Last field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListVerificationsIdentityProfileRequest) SetLast(last *int) {
	l.Last = last
	l.require(listVerificationsIdentityProfileRequestFieldLast)
}

var (
	retrieveIdentityProfileRequestFieldID = big.NewInt(1 << 0)
)

type RetrieveIdentityProfileRequest struct {
	// The unique identifier of the identity profile (idpf_xxx).
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RetrieveIdentityProfileRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveIdentityProfileRequest) SetID(id string) {
	r.ID = id
	r.require(retrieveIdentityProfileRequestFieldID)
}

// A consolidated identity or business profile synced from verification provider data.
var (
	identityProfileFieldBusinessAddress   = big.NewInt(1 << 0)
	identityProfileFieldBusinessName      = big.NewInt(1 << 1)
	identityProfileFieldBusinessStructure = big.NewInt(1 << 2)
	identityProfileFieldCountry           = big.NewInt(1 << 3)
	identityProfileFieldCreatedAt         = big.NewInt(1 << 4)
	identityProfileFieldDateOfBirth       = big.NewInt(1 << 5)
	identityProfileFieldEmail             = big.NewInt(1 << 6)
	identityProfileFieldFirstName         = big.NewInt(1 << 7)
	identityProfileFieldID                = big.NewInt(1 << 8)
	identityProfileFieldLastName          = big.NewInt(1 << 9)
	identityProfileFieldLinkedCompanies   = big.NewInt(1 << 10)
	identityProfileFieldPayoutStatus      = big.NewInt(1 << 11)
	identityProfileFieldPayoutsEnabled    = big.NewInt(1 << 12)
	identityProfileFieldPersonalAddress   = big.NewInt(1 << 13)
	identityProfileFieldPhone             = big.NewInt(1 << 14)
	identityProfileFieldProfileType       = big.NewInt(1 << 15)
	identityProfileFieldStatus            = big.NewInt(1 << 16)
	identityProfileFieldUpdatedAt         = big.NewInt(1 << 17)
	identityProfileFieldVerifications     = big.NewInt(1 << 18)
)

type IdentityProfile struct {
	// Registered business address reported by the identity provider. Present on `business` profiles.
	BusinessAddress *IdentityProfileBusinessAddress `json:"business_address,omitempty" url:"business_address,omitempty"`
	// Business entity name. Present on `business` profiles.
	BusinessName *string `json:"business_name,omitempty" url:"business_name,omitempty"`
	// Reported legal structure of a business profile (e.g. `corp`, `llc`). Provider-specific values; present on `business` profiles.
	BusinessStructure *string `json:"business_structure,omitempty" url:"business_structure,omitempty"`
	// ISO 3166-1 alpha-2 country code reported by the identity provider, such as `US` or `GB`. For individuals this is the country of citizenship or residence; for businesses, the country of incorporation.
	Country *string `json:"country,omitempty" url:"country,omitempty"`
	// When the identity profile was first created.
	CreatedAt time.Time `json:"created_at" url:"created_at"`
	// ISO date (`YYYY-MM-DD`) reported by the identity provider. Present on `individual` profiles.
	DateOfBirth *string `json:"date_of_birth,omitempty" url:"date_of_birth,omitempty"`
	// Email address reported by the identity provider. Typically present on `individual` profiles.
	Email *string `json:"email,omitempty" url:"email,omitempty"`
	// Individual's first name.
	FirstName *string `json:"first_name,omitempty" url:"first_name,omitempty"`
	// The tag of the identity profile (idpf_xxx).
	ID string `json:"id" url:"id"`
	// Individual's last name.
	LastName *string `json:"last_name,omitempty" url:"last_name,omitempty"`
	// The companies this identity profile is currently linked to. Only populated for direct Whop user sessions; always empty when authenticated via API key, app, or OAuth scope (a single identity can be linked to companies the calling platform is not entitled to see).
	LinkedCompanies []*IdentityProfileLinkedCompaniesItem `json:"linked_companies" url:"linked_companies"`
	// Progress of payout-account setup for this profile, independent of holds. `connected` means onboarding is complete; a `connected` status paired with `payouts_enabled: false` indicates an active account restriction rather than incomplete setup.
	PayoutStatus PayoutAccountCalculatedStatuses `json:"payout_status" url:"payout_status"`
	// Whether this profile can receive payouts right now. True only when payout onboarding is complete and no payout holds are active on the linked account. Treat this as the single source of truth for payout readiness.
	PayoutsEnabled bool `json:"payouts_enabled" url:"payouts_enabled"`
	// Residential address reported by the identity provider. Present on `individual` profiles.
	PersonalAddress *IdentityProfilePersonalAddress `json:"personal_address,omitempty" url:"personal_address,omitempty"`
	// Phone number reported by the identity provider. Typically present on `individual` profiles.
	Phone *string `json:"phone,omitempty" url:"phone,omitempty"`
	// Whether this is an 'individual' or 'business' profile.
	ProfileType string `json:"profile_type" url:"profile_type"`
	// Derived verification status across all linked verifications. Returns `action_required` whenever the profile has an open request for information (whether a verification, payout, or audit RFI) — i.e. the merchant must submit something before it is in good standing.
	Status IdentityProfileStatuses `json:"status" url:"status"`
	// When the identity profile was last synced from a verification.
	UpdatedAt time.Time `json:"updated_at" url:"updated_at"`
	// All verification attempts attached to this identity profile, ordered most-recent first.
	Verifications []*IdentityProfileVerificationsItem `json:"verifications" url:"verifications"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *IdentityProfile) GetBusinessAddress() *IdentityProfileBusinessAddress {
	if i == nil {
		return nil
	}
	return i.BusinessAddress
}

func (i *IdentityProfile) GetBusinessName() *string {
	if i == nil {
		return nil
	}
	return i.BusinessName
}

func (i *IdentityProfile) GetBusinessStructure() *string {
	if i == nil {
		return nil
	}
	return i.BusinessStructure
}

func (i *IdentityProfile) GetCountry() *string {
	if i == nil {
		return nil
	}
	return i.Country
}

func (i *IdentityProfile) GetCreatedAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.CreatedAt
}

func (i *IdentityProfile) GetDateOfBirth() *string {
	if i == nil {
		return nil
	}
	return i.DateOfBirth
}

func (i *IdentityProfile) GetEmail() *string {
	if i == nil {
		return nil
	}
	return i.Email
}

func (i *IdentityProfile) GetFirstName() *string {
	if i == nil {
		return nil
	}
	return i.FirstName
}

func (i *IdentityProfile) GetID() string {
	if i == nil {
		return ""
	}
	return i.ID
}

func (i *IdentityProfile) GetLastName() *string {
	if i == nil {
		return nil
	}
	return i.LastName
}

func (i *IdentityProfile) GetLinkedCompanies() []*IdentityProfileLinkedCompaniesItem {
	if i == nil {
		return nil
	}
	return i.LinkedCompanies
}

func (i *IdentityProfile) GetPayoutStatus() PayoutAccountCalculatedStatuses {
	if i == nil {
		return ""
	}
	return i.PayoutStatus
}

func (i *IdentityProfile) GetPayoutsEnabled() bool {
	if i == nil {
		return false
	}
	return i.PayoutsEnabled
}

func (i *IdentityProfile) GetPersonalAddress() *IdentityProfilePersonalAddress {
	if i == nil {
		return nil
	}
	return i.PersonalAddress
}

func (i *IdentityProfile) GetPhone() *string {
	if i == nil {
		return nil
	}
	return i.Phone
}

func (i *IdentityProfile) GetProfileType() string {
	if i == nil {
		return ""
	}
	return i.ProfileType
}

func (i *IdentityProfile) GetStatus() IdentityProfileStatuses {
	if i == nil {
		return ""
	}
	return i.Status
}

func (i *IdentityProfile) GetUpdatedAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.UpdatedAt
}

func (i *IdentityProfile) GetVerifications() []*IdentityProfileVerificationsItem {
	if i == nil {
		return nil
	}
	return i.Verifications
}

func (i *IdentityProfile) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *IdentityProfile) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetBusinessAddress sets the BusinessAddress field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfile) SetBusinessAddress(businessAddress *IdentityProfileBusinessAddress) {
	i.BusinessAddress = businessAddress
	i.require(identityProfileFieldBusinessAddress)
}

// SetBusinessName sets the BusinessName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfile) SetBusinessName(businessName *string) {
	i.BusinessName = businessName
	i.require(identityProfileFieldBusinessName)
}

// SetBusinessStructure sets the BusinessStructure field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfile) SetBusinessStructure(businessStructure *string) {
	i.BusinessStructure = businessStructure
	i.require(identityProfileFieldBusinessStructure)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfile) SetCountry(country *string) {
	i.Country = country
	i.require(identityProfileFieldCountry)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfile) SetCreatedAt(createdAt time.Time) {
	i.CreatedAt = createdAt
	i.require(identityProfileFieldCreatedAt)
}

// SetDateOfBirth sets the DateOfBirth field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfile) SetDateOfBirth(dateOfBirth *string) {
	i.DateOfBirth = dateOfBirth
	i.require(identityProfileFieldDateOfBirth)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfile) SetEmail(email *string) {
	i.Email = email
	i.require(identityProfileFieldEmail)
}

// SetFirstName sets the FirstName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfile) SetFirstName(firstName *string) {
	i.FirstName = firstName
	i.require(identityProfileFieldFirstName)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfile) SetID(id string) {
	i.ID = id
	i.require(identityProfileFieldID)
}

// SetLastName sets the LastName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfile) SetLastName(lastName *string) {
	i.LastName = lastName
	i.require(identityProfileFieldLastName)
}

// SetLinkedCompanies sets the LinkedCompanies field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfile) SetLinkedCompanies(linkedCompanies []*IdentityProfileLinkedCompaniesItem) {
	i.LinkedCompanies = linkedCompanies
	i.require(identityProfileFieldLinkedCompanies)
}

// SetPayoutStatus sets the PayoutStatus field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfile) SetPayoutStatus(payoutStatus PayoutAccountCalculatedStatuses) {
	i.PayoutStatus = payoutStatus
	i.require(identityProfileFieldPayoutStatus)
}

// SetPayoutsEnabled sets the PayoutsEnabled field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfile) SetPayoutsEnabled(payoutsEnabled bool) {
	i.PayoutsEnabled = payoutsEnabled
	i.require(identityProfileFieldPayoutsEnabled)
}

// SetPersonalAddress sets the PersonalAddress field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfile) SetPersonalAddress(personalAddress *IdentityProfilePersonalAddress) {
	i.PersonalAddress = personalAddress
	i.require(identityProfileFieldPersonalAddress)
}

// SetPhone sets the Phone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfile) SetPhone(phone *string) {
	i.Phone = phone
	i.require(identityProfileFieldPhone)
}

// SetProfileType sets the ProfileType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfile) SetProfileType(profileType string) {
	i.ProfileType = profileType
	i.require(identityProfileFieldProfileType)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfile) SetStatus(status IdentityProfileStatuses) {
	i.Status = status
	i.require(identityProfileFieldStatus)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfile) SetUpdatedAt(updatedAt time.Time) {
	i.UpdatedAt = updatedAt
	i.require(identityProfileFieldUpdatedAt)
}

// SetVerifications sets the Verifications field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfile) SetVerifications(verifications []*IdentityProfileVerificationsItem) {
	i.Verifications = verifications
	i.require(identityProfileFieldVerifications)
}

func (i *IdentityProfile) UnmarshalJSON(data []byte) error {
	type embed IdentityProfile
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
		UpdatedAt *internal.DateTime `json:"updated_at"`
	}{
		embed: embed(*i),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*i = IdentityProfile(unmarshaler.embed)
	i.CreatedAt = unmarshaler.CreatedAt.Time()
	i.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *IdentityProfile) MarshalJSON() ([]byte, error) {
	type embed IdentityProfile
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
		UpdatedAt *internal.DateTime `json:"updated_at"`
	}{
		embed:     embed(*i),
		CreatedAt: internal.NewDateTime(i.CreatedAt),
		UpdatedAt: internal.NewDateTime(i.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *IdentityProfile) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// Registered business address reported by the identity provider. Present on `business` profiles.
var (
	identityProfileBusinessAddressFieldCity       = big.NewInt(1 << 0)
	identityProfileBusinessAddressFieldCountry    = big.NewInt(1 << 1)
	identityProfileBusinessAddressFieldLine1      = big.NewInt(1 << 2)
	identityProfileBusinessAddressFieldLine2      = big.NewInt(1 << 3)
	identityProfileBusinessAddressFieldPostalCode = big.NewInt(1 << 4)
	identityProfileBusinessAddressFieldState      = big.NewInt(1 << 5)
)

type IdentityProfileBusinessAddress struct {
	// The city of the address.
	City *string `json:"city,omitempty" url:"city,omitempty"`
	// The country of the address.
	Country *string `json:"country,omitempty" url:"country,omitempty"`
	// The line 1 of the address.
	Line1 *string `json:"line1,omitempty" url:"line1,omitempty"`
	// The line 2 of the address.
	Line2 *string `json:"line2,omitempty" url:"line2,omitempty"`
	// The postal code of the address.
	PostalCode *string `json:"postal_code,omitempty" url:"postal_code,omitempty"`
	// The state of the address.
	State *string `json:"state,omitempty" url:"state,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *IdentityProfileBusinessAddress) GetCity() *string {
	if i == nil {
		return nil
	}
	return i.City
}

func (i *IdentityProfileBusinessAddress) GetCountry() *string {
	if i == nil {
		return nil
	}
	return i.Country
}

func (i *IdentityProfileBusinessAddress) GetLine1() *string {
	if i == nil {
		return nil
	}
	return i.Line1
}

func (i *IdentityProfileBusinessAddress) GetLine2() *string {
	if i == nil {
		return nil
	}
	return i.Line2
}

func (i *IdentityProfileBusinessAddress) GetPostalCode() *string {
	if i == nil {
		return nil
	}
	return i.PostalCode
}

func (i *IdentityProfileBusinessAddress) GetState() *string {
	if i == nil {
		return nil
	}
	return i.State
}

func (i *IdentityProfileBusinessAddress) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *IdentityProfileBusinessAddress) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetCity sets the City field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileBusinessAddress) SetCity(city *string) {
	i.City = city
	i.require(identityProfileBusinessAddressFieldCity)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileBusinessAddress) SetCountry(country *string) {
	i.Country = country
	i.require(identityProfileBusinessAddressFieldCountry)
}

// SetLine1 sets the Line1 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileBusinessAddress) SetLine1(line1 *string) {
	i.Line1 = line1
	i.require(identityProfileBusinessAddressFieldLine1)
}

// SetLine2 sets the Line2 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileBusinessAddress) SetLine2(line2 *string) {
	i.Line2 = line2
	i.require(identityProfileBusinessAddressFieldLine2)
}

// SetPostalCode sets the PostalCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileBusinessAddress) SetPostalCode(postalCode *string) {
	i.PostalCode = postalCode
	i.require(identityProfileBusinessAddressFieldPostalCode)
}

// SetState sets the State field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileBusinessAddress) SetState(state *string) {
	i.State = state
	i.require(identityProfileBusinessAddressFieldState)
}

func (i *IdentityProfileBusinessAddress) UnmarshalJSON(data []byte) error {
	type unmarshaler IdentityProfileBusinessAddress
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = IdentityProfileBusinessAddress(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *IdentityProfileBusinessAddress) MarshalJSON() ([]byte, error) {
	type embed IdentityProfileBusinessAddress
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *IdentityProfileBusinessAddress) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// The kind of identity profile (individual vs business).
type IdentityProfileKinds string

const (
	IdentityProfileKindsIndividual IdentityProfileKinds = "individual"
	IdentityProfileKindsBusiness   IdentityProfileKinds = "business"
)

func NewIdentityProfileKindsFromString(s string) (IdentityProfileKinds, error) {
	switch s {
	case "individual":
		return IdentityProfileKindsIndividual, nil
	case "business":
		return IdentityProfileKindsBusiness, nil
	}
	var t IdentityProfileKinds
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (i IdentityProfileKinds) Ptr() *IdentityProfileKinds {
	return &i
}

// A company is a seller on Whop. Companies own products, manage members, and receive payouts.
var (
	identityProfileLinkedCompaniesItemFieldID    = big.NewInt(1 << 0)
	identityProfileLinkedCompaniesItemFieldTitle = big.NewInt(1 << 1)
)

type IdentityProfileLinkedCompaniesItem struct {
	// The unique identifier for the company.
	ID string `json:"id" url:"id"`
	// The display name of the company shown to customers.
	Title string `json:"title" url:"title"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *IdentityProfileLinkedCompaniesItem) GetID() string {
	if i == nil {
		return ""
	}
	return i.ID
}

func (i *IdentityProfileLinkedCompaniesItem) GetTitle() string {
	if i == nil {
		return ""
	}
	return i.Title
}

func (i *IdentityProfileLinkedCompaniesItem) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *IdentityProfileLinkedCompaniesItem) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileLinkedCompaniesItem) SetID(id string) {
	i.ID = id
	i.require(identityProfileLinkedCompaniesItemFieldID)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileLinkedCompaniesItem) SetTitle(title string) {
	i.Title = title
	i.require(identityProfileLinkedCompaniesItemFieldTitle)
}

func (i *IdentityProfileLinkedCompaniesItem) UnmarshalJSON(data []byte) error {
	type unmarshaler IdentityProfileLinkedCompaniesItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = IdentityProfileLinkedCompaniesItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *IdentityProfileLinkedCompaniesItem) MarshalJSON() ([]byte, error) {
	type embed IdentityProfileLinkedCompaniesItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *IdentityProfileLinkedCompaniesItem) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// A consolidated identity or business profile synced from verification provider data.
var (
	identityProfileListItemFieldBusinessAddress   = big.NewInt(1 << 0)
	identityProfileListItemFieldBusinessName      = big.NewInt(1 << 1)
	identityProfileListItemFieldBusinessStructure = big.NewInt(1 << 2)
	identityProfileListItemFieldCountry           = big.NewInt(1 << 3)
	identityProfileListItemFieldCreatedAt         = big.NewInt(1 << 4)
	identityProfileListItemFieldDateOfBirth       = big.NewInt(1 << 5)
	identityProfileListItemFieldEmail             = big.NewInt(1 << 6)
	identityProfileListItemFieldFirstName         = big.NewInt(1 << 7)
	identityProfileListItemFieldID                = big.NewInt(1 << 8)
	identityProfileListItemFieldLastName          = big.NewInt(1 << 9)
	identityProfileListItemFieldLinkedCompanies   = big.NewInt(1 << 10)
	identityProfileListItemFieldPayoutStatus      = big.NewInt(1 << 11)
	identityProfileListItemFieldPayoutsEnabled    = big.NewInt(1 << 12)
	identityProfileListItemFieldPersonalAddress   = big.NewInt(1 << 13)
	identityProfileListItemFieldPhone             = big.NewInt(1 << 14)
	identityProfileListItemFieldProfileType       = big.NewInt(1 << 15)
	identityProfileListItemFieldStatus            = big.NewInt(1 << 16)
	identityProfileListItemFieldUpdatedAt         = big.NewInt(1 << 17)
	identityProfileListItemFieldVerifications     = big.NewInt(1 << 18)
)

type IdentityProfileListItem struct {
	// Registered business address reported by the identity provider. Present on `business` profiles.
	BusinessAddress *IdentityProfileListItemBusinessAddress `json:"business_address,omitempty" url:"business_address,omitempty"`
	// Business entity name. Present on `business` profiles.
	BusinessName *string `json:"business_name,omitempty" url:"business_name,omitempty"`
	// Reported legal structure of a business profile (e.g. `corp`, `llc`). Provider-specific values; present on `business` profiles.
	BusinessStructure *string `json:"business_structure,omitempty" url:"business_structure,omitempty"`
	// ISO 3166-1 alpha-2 country code reported by the identity provider, such as `US` or `GB`. For individuals this is the country of citizenship or residence; for businesses, the country of incorporation.
	Country *string `json:"country,omitempty" url:"country,omitempty"`
	// When the identity profile was first created.
	CreatedAt time.Time `json:"created_at" url:"created_at"`
	// ISO date (`YYYY-MM-DD`) reported by the identity provider. Present on `individual` profiles.
	DateOfBirth *string `json:"date_of_birth,omitempty" url:"date_of_birth,omitempty"`
	// Email address reported by the identity provider. Typically present on `individual` profiles.
	Email *string `json:"email,omitempty" url:"email,omitempty"`
	// Individual's first name.
	FirstName *string `json:"first_name,omitempty" url:"first_name,omitempty"`
	// The tag of the identity profile (idpf_xxx).
	ID string `json:"id" url:"id"`
	// Individual's last name.
	LastName *string `json:"last_name,omitempty" url:"last_name,omitempty"`
	// The companies this identity profile is currently linked to. Only populated for direct Whop user sessions; always empty when authenticated via API key, app, or OAuth scope (a single identity can be linked to companies the calling platform is not entitled to see).
	LinkedCompanies []*IdentityProfileListItemLinkedCompaniesItem `json:"linked_companies" url:"linked_companies"`
	// Progress of payout-account setup for this profile, independent of holds. `connected` means onboarding is complete; a `connected` status paired with `payouts_enabled: false` indicates an active account restriction rather than incomplete setup.
	PayoutStatus PayoutAccountCalculatedStatuses `json:"payout_status" url:"payout_status"`
	// Whether this profile can receive payouts right now. True only when payout onboarding is complete and no payout holds are active on the linked account. Treat this as the single source of truth for payout readiness.
	PayoutsEnabled bool `json:"payouts_enabled" url:"payouts_enabled"`
	// Residential address reported by the identity provider. Present on `individual` profiles.
	PersonalAddress *IdentityProfileListItemPersonalAddress `json:"personal_address,omitempty" url:"personal_address,omitempty"`
	// Phone number reported by the identity provider. Typically present on `individual` profiles.
	Phone *string `json:"phone,omitempty" url:"phone,omitempty"`
	// Whether this is an 'individual' or 'business' profile.
	ProfileType string `json:"profile_type" url:"profile_type"`
	// Derived verification status across all linked verifications. Returns `action_required` whenever the profile has an open request for information (whether a verification, payout, or audit RFI) — i.e. the merchant must submit something before it is in good standing.
	Status IdentityProfileStatuses `json:"status" url:"status"`
	// When the identity profile was last synced from a verification.
	UpdatedAt time.Time `json:"updated_at" url:"updated_at"`
	// All verification attempts attached to this identity profile, ordered most-recent first.
	Verifications []*IdentityProfileListItemVerificationsItem `json:"verifications" url:"verifications"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *IdentityProfileListItem) GetBusinessAddress() *IdentityProfileListItemBusinessAddress {
	if i == nil {
		return nil
	}
	return i.BusinessAddress
}

func (i *IdentityProfileListItem) GetBusinessName() *string {
	if i == nil {
		return nil
	}
	return i.BusinessName
}

func (i *IdentityProfileListItem) GetBusinessStructure() *string {
	if i == nil {
		return nil
	}
	return i.BusinessStructure
}

func (i *IdentityProfileListItem) GetCountry() *string {
	if i == nil {
		return nil
	}
	return i.Country
}

func (i *IdentityProfileListItem) GetCreatedAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.CreatedAt
}

func (i *IdentityProfileListItem) GetDateOfBirth() *string {
	if i == nil {
		return nil
	}
	return i.DateOfBirth
}

func (i *IdentityProfileListItem) GetEmail() *string {
	if i == nil {
		return nil
	}
	return i.Email
}

func (i *IdentityProfileListItem) GetFirstName() *string {
	if i == nil {
		return nil
	}
	return i.FirstName
}

func (i *IdentityProfileListItem) GetID() string {
	if i == nil {
		return ""
	}
	return i.ID
}

func (i *IdentityProfileListItem) GetLastName() *string {
	if i == nil {
		return nil
	}
	return i.LastName
}

func (i *IdentityProfileListItem) GetLinkedCompanies() []*IdentityProfileListItemLinkedCompaniesItem {
	if i == nil {
		return nil
	}
	return i.LinkedCompanies
}

func (i *IdentityProfileListItem) GetPayoutStatus() PayoutAccountCalculatedStatuses {
	if i == nil {
		return ""
	}
	return i.PayoutStatus
}

func (i *IdentityProfileListItem) GetPayoutsEnabled() bool {
	if i == nil {
		return false
	}
	return i.PayoutsEnabled
}

func (i *IdentityProfileListItem) GetPersonalAddress() *IdentityProfileListItemPersonalAddress {
	if i == nil {
		return nil
	}
	return i.PersonalAddress
}

func (i *IdentityProfileListItem) GetPhone() *string {
	if i == nil {
		return nil
	}
	return i.Phone
}

func (i *IdentityProfileListItem) GetProfileType() string {
	if i == nil {
		return ""
	}
	return i.ProfileType
}

func (i *IdentityProfileListItem) GetStatus() IdentityProfileStatuses {
	if i == nil {
		return ""
	}
	return i.Status
}

func (i *IdentityProfileListItem) GetUpdatedAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.UpdatedAt
}

func (i *IdentityProfileListItem) GetVerifications() []*IdentityProfileListItemVerificationsItem {
	if i == nil {
		return nil
	}
	return i.Verifications
}

func (i *IdentityProfileListItem) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *IdentityProfileListItem) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetBusinessAddress sets the BusinessAddress field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItem) SetBusinessAddress(businessAddress *IdentityProfileListItemBusinessAddress) {
	i.BusinessAddress = businessAddress
	i.require(identityProfileListItemFieldBusinessAddress)
}

// SetBusinessName sets the BusinessName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItem) SetBusinessName(businessName *string) {
	i.BusinessName = businessName
	i.require(identityProfileListItemFieldBusinessName)
}

// SetBusinessStructure sets the BusinessStructure field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItem) SetBusinessStructure(businessStructure *string) {
	i.BusinessStructure = businessStructure
	i.require(identityProfileListItemFieldBusinessStructure)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItem) SetCountry(country *string) {
	i.Country = country
	i.require(identityProfileListItemFieldCountry)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItem) SetCreatedAt(createdAt time.Time) {
	i.CreatedAt = createdAt
	i.require(identityProfileListItemFieldCreatedAt)
}

// SetDateOfBirth sets the DateOfBirth field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItem) SetDateOfBirth(dateOfBirth *string) {
	i.DateOfBirth = dateOfBirth
	i.require(identityProfileListItemFieldDateOfBirth)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItem) SetEmail(email *string) {
	i.Email = email
	i.require(identityProfileListItemFieldEmail)
}

// SetFirstName sets the FirstName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItem) SetFirstName(firstName *string) {
	i.FirstName = firstName
	i.require(identityProfileListItemFieldFirstName)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItem) SetID(id string) {
	i.ID = id
	i.require(identityProfileListItemFieldID)
}

// SetLastName sets the LastName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItem) SetLastName(lastName *string) {
	i.LastName = lastName
	i.require(identityProfileListItemFieldLastName)
}

// SetLinkedCompanies sets the LinkedCompanies field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItem) SetLinkedCompanies(linkedCompanies []*IdentityProfileListItemLinkedCompaniesItem) {
	i.LinkedCompanies = linkedCompanies
	i.require(identityProfileListItemFieldLinkedCompanies)
}

// SetPayoutStatus sets the PayoutStatus field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItem) SetPayoutStatus(payoutStatus PayoutAccountCalculatedStatuses) {
	i.PayoutStatus = payoutStatus
	i.require(identityProfileListItemFieldPayoutStatus)
}

// SetPayoutsEnabled sets the PayoutsEnabled field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItem) SetPayoutsEnabled(payoutsEnabled bool) {
	i.PayoutsEnabled = payoutsEnabled
	i.require(identityProfileListItemFieldPayoutsEnabled)
}

// SetPersonalAddress sets the PersonalAddress field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItem) SetPersonalAddress(personalAddress *IdentityProfileListItemPersonalAddress) {
	i.PersonalAddress = personalAddress
	i.require(identityProfileListItemFieldPersonalAddress)
}

// SetPhone sets the Phone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItem) SetPhone(phone *string) {
	i.Phone = phone
	i.require(identityProfileListItemFieldPhone)
}

// SetProfileType sets the ProfileType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItem) SetProfileType(profileType string) {
	i.ProfileType = profileType
	i.require(identityProfileListItemFieldProfileType)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItem) SetStatus(status IdentityProfileStatuses) {
	i.Status = status
	i.require(identityProfileListItemFieldStatus)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItem) SetUpdatedAt(updatedAt time.Time) {
	i.UpdatedAt = updatedAt
	i.require(identityProfileListItemFieldUpdatedAt)
}

// SetVerifications sets the Verifications field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItem) SetVerifications(verifications []*IdentityProfileListItemVerificationsItem) {
	i.Verifications = verifications
	i.require(identityProfileListItemFieldVerifications)
}

func (i *IdentityProfileListItem) UnmarshalJSON(data []byte) error {
	type embed IdentityProfileListItem
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
		UpdatedAt *internal.DateTime `json:"updated_at"`
	}{
		embed: embed(*i),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*i = IdentityProfileListItem(unmarshaler.embed)
	i.CreatedAt = unmarshaler.CreatedAt.Time()
	i.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *IdentityProfileListItem) MarshalJSON() ([]byte, error) {
	type embed IdentityProfileListItem
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
		UpdatedAt *internal.DateTime `json:"updated_at"`
	}{
		embed:     embed(*i),
		CreatedAt: internal.NewDateTime(i.CreatedAt),
		UpdatedAt: internal.NewDateTime(i.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *IdentityProfileListItem) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// Registered business address reported by the identity provider. Present on `business` profiles.
var (
	identityProfileListItemBusinessAddressFieldCity       = big.NewInt(1 << 0)
	identityProfileListItemBusinessAddressFieldCountry    = big.NewInt(1 << 1)
	identityProfileListItemBusinessAddressFieldLine1      = big.NewInt(1 << 2)
	identityProfileListItemBusinessAddressFieldLine2      = big.NewInt(1 << 3)
	identityProfileListItemBusinessAddressFieldPostalCode = big.NewInt(1 << 4)
	identityProfileListItemBusinessAddressFieldState      = big.NewInt(1 << 5)
)

type IdentityProfileListItemBusinessAddress struct {
	// The city of the address.
	City *string `json:"city,omitempty" url:"city,omitempty"`
	// The country of the address.
	Country *string `json:"country,omitempty" url:"country,omitempty"`
	// The line 1 of the address.
	Line1 *string `json:"line1,omitempty" url:"line1,omitempty"`
	// The line 2 of the address.
	Line2 *string `json:"line2,omitempty" url:"line2,omitempty"`
	// The postal code of the address.
	PostalCode *string `json:"postal_code,omitempty" url:"postal_code,omitempty"`
	// The state of the address.
	State *string `json:"state,omitempty" url:"state,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *IdentityProfileListItemBusinessAddress) GetCity() *string {
	if i == nil {
		return nil
	}
	return i.City
}

func (i *IdentityProfileListItemBusinessAddress) GetCountry() *string {
	if i == nil {
		return nil
	}
	return i.Country
}

func (i *IdentityProfileListItemBusinessAddress) GetLine1() *string {
	if i == nil {
		return nil
	}
	return i.Line1
}

func (i *IdentityProfileListItemBusinessAddress) GetLine2() *string {
	if i == nil {
		return nil
	}
	return i.Line2
}

func (i *IdentityProfileListItemBusinessAddress) GetPostalCode() *string {
	if i == nil {
		return nil
	}
	return i.PostalCode
}

func (i *IdentityProfileListItemBusinessAddress) GetState() *string {
	if i == nil {
		return nil
	}
	return i.State
}

func (i *IdentityProfileListItemBusinessAddress) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *IdentityProfileListItemBusinessAddress) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetCity sets the City field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItemBusinessAddress) SetCity(city *string) {
	i.City = city
	i.require(identityProfileListItemBusinessAddressFieldCity)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItemBusinessAddress) SetCountry(country *string) {
	i.Country = country
	i.require(identityProfileListItemBusinessAddressFieldCountry)
}

// SetLine1 sets the Line1 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItemBusinessAddress) SetLine1(line1 *string) {
	i.Line1 = line1
	i.require(identityProfileListItemBusinessAddressFieldLine1)
}

// SetLine2 sets the Line2 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItemBusinessAddress) SetLine2(line2 *string) {
	i.Line2 = line2
	i.require(identityProfileListItemBusinessAddressFieldLine2)
}

// SetPostalCode sets the PostalCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItemBusinessAddress) SetPostalCode(postalCode *string) {
	i.PostalCode = postalCode
	i.require(identityProfileListItemBusinessAddressFieldPostalCode)
}

// SetState sets the State field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItemBusinessAddress) SetState(state *string) {
	i.State = state
	i.require(identityProfileListItemBusinessAddressFieldState)
}

func (i *IdentityProfileListItemBusinessAddress) UnmarshalJSON(data []byte) error {
	type unmarshaler IdentityProfileListItemBusinessAddress
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = IdentityProfileListItemBusinessAddress(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *IdentityProfileListItemBusinessAddress) MarshalJSON() ([]byte, error) {
	type embed IdentityProfileListItemBusinessAddress
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *IdentityProfileListItemBusinessAddress) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// A company is a seller on Whop. Companies own products, manage members, and receive payouts.
var (
	identityProfileListItemLinkedCompaniesItemFieldID    = big.NewInt(1 << 0)
	identityProfileListItemLinkedCompaniesItemFieldTitle = big.NewInt(1 << 1)
)

type IdentityProfileListItemLinkedCompaniesItem struct {
	// The unique identifier for the company.
	ID string `json:"id" url:"id"`
	// The display name of the company shown to customers.
	Title string `json:"title" url:"title"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *IdentityProfileListItemLinkedCompaniesItem) GetID() string {
	if i == nil {
		return ""
	}
	return i.ID
}

func (i *IdentityProfileListItemLinkedCompaniesItem) GetTitle() string {
	if i == nil {
		return ""
	}
	return i.Title
}

func (i *IdentityProfileListItemLinkedCompaniesItem) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *IdentityProfileListItemLinkedCompaniesItem) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItemLinkedCompaniesItem) SetID(id string) {
	i.ID = id
	i.require(identityProfileListItemLinkedCompaniesItemFieldID)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItemLinkedCompaniesItem) SetTitle(title string) {
	i.Title = title
	i.require(identityProfileListItemLinkedCompaniesItemFieldTitle)
}

func (i *IdentityProfileListItemLinkedCompaniesItem) UnmarshalJSON(data []byte) error {
	type unmarshaler IdentityProfileListItemLinkedCompaniesItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = IdentityProfileListItemLinkedCompaniesItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *IdentityProfileListItemLinkedCompaniesItem) MarshalJSON() ([]byte, error) {
	type embed IdentityProfileListItemLinkedCompaniesItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *IdentityProfileListItemLinkedCompaniesItem) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// Residential address reported by the identity provider. Present on `individual` profiles.
var (
	identityProfileListItemPersonalAddressFieldCity       = big.NewInt(1 << 0)
	identityProfileListItemPersonalAddressFieldCountry    = big.NewInt(1 << 1)
	identityProfileListItemPersonalAddressFieldLine1      = big.NewInt(1 << 2)
	identityProfileListItemPersonalAddressFieldLine2      = big.NewInt(1 << 3)
	identityProfileListItemPersonalAddressFieldPostalCode = big.NewInt(1 << 4)
	identityProfileListItemPersonalAddressFieldState      = big.NewInt(1 << 5)
)

type IdentityProfileListItemPersonalAddress struct {
	// The city of the address.
	City *string `json:"city,omitempty" url:"city,omitempty"`
	// The country of the address.
	Country *string `json:"country,omitempty" url:"country,omitempty"`
	// The line 1 of the address.
	Line1 *string `json:"line1,omitempty" url:"line1,omitempty"`
	// The line 2 of the address.
	Line2 *string `json:"line2,omitempty" url:"line2,omitempty"`
	// The postal code of the address.
	PostalCode *string `json:"postal_code,omitempty" url:"postal_code,omitempty"`
	// The state of the address.
	State *string `json:"state,omitempty" url:"state,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *IdentityProfileListItemPersonalAddress) GetCity() *string {
	if i == nil {
		return nil
	}
	return i.City
}

func (i *IdentityProfileListItemPersonalAddress) GetCountry() *string {
	if i == nil {
		return nil
	}
	return i.Country
}

func (i *IdentityProfileListItemPersonalAddress) GetLine1() *string {
	if i == nil {
		return nil
	}
	return i.Line1
}

func (i *IdentityProfileListItemPersonalAddress) GetLine2() *string {
	if i == nil {
		return nil
	}
	return i.Line2
}

func (i *IdentityProfileListItemPersonalAddress) GetPostalCode() *string {
	if i == nil {
		return nil
	}
	return i.PostalCode
}

func (i *IdentityProfileListItemPersonalAddress) GetState() *string {
	if i == nil {
		return nil
	}
	return i.State
}

func (i *IdentityProfileListItemPersonalAddress) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *IdentityProfileListItemPersonalAddress) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetCity sets the City field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItemPersonalAddress) SetCity(city *string) {
	i.City = city
	i.require(identityProfileListItemPersonalAddressFieldCity)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItemPersonalAddress) SetCountry(country *string) {
	i.Country = country
	i.require(identityProfileListItemPersonalAddressFieldCountry)
}

// SetLine1 sets the Line1 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItemPersonalAddress) SetLine1(line1 *string) {
	i.Line1 = line1
	i.require(identityProfileListItemPersonalAddressFieldLine1)
}

// SetLine2 sets the Line2 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItemPersonalAddress) SetLine2(line2 *string) {
	i.Line2 = line2
	i.require(identityProfileListItemPersonalAddressFieldLine2)
}

// SetPostalCode sets the PostalCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItemPersonalAddress) SetPostalCode(postalCode *string) {
	i.PostalCode = postalCode
	i.require(identityProfileListItemPersonalAddressFieldPostalCode)
}

// SetState sets the State field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItemPersonalAddress) SetState(state *string) {
	i.State = state
	i.require(identityProfileListItemPersonalAddressFieldState)
}

func (i *IdentityProfileListItemPersonalAddress) UnmarshalJSON(data []byte) error {
	type unmarshaler IdentityProfileListItemPersonalAddress
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = IdentityProfileListItemPersonalAddress(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *IdentityProfileListItemPersonalAddress) MarshalJSON() ([]byte, error) {
	type embed IdentityProfileListItemPersonalAddress
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *IdentityProfileListItemPersonalAddress) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// An identity verification session used to confirm a person or entity's identity for payout account eligibility.
var (
	identityProfileListItemVerificationsItemFieldCreatedAt       = big.NewInt(1 << 0)
	identityProfileListItemVerificationsItemFieldID              = big.NewInt(1 << 1)
	identityProfileListItemVerificationsItemFieldLastErrorCode   = big.NewInt(1 << 2)
	identityProfileListItemVerificationsItemFieldLastErrorReason = big.NewInt(1 << 3)
	identityProfileListItemVerificationsItemFieldSessionURL      = big.NewInt(1 << 4)
	identityProfileListItemVerificationsItemFieldStatus          = big.NewInt(1 << 5)
)

type IdentityProfileListItemVerificationsItem struct {
	// When the verification record was created.
	CreatedAt time.Time `json:"created_at" url:"created_at"`
	// The numeric id of the verification record.
	ID string `json:"id" url:"id"`
	// The most recent error code returned during verification. Null if no error has occurred.
	LastErrorCode *VerificationErrorCodes `json:"last_error_code,omitempty" url:"last_error_code,omitempty"`
	// A human-readable explanation of the most recent verification error. Null if no error has occurred.
	LastErrorReason *string `json:"last_error_reason,omitempty" url:"last_error_reason,omitempty"`
	// A URL the user can visit to complete the verification process. Null if the session does not require user interaction.
	SessionURL *string `json:"session_url,omitempty" url:"session_url,omitempty"`
	// The current status of this verification session.
	Status VerificationStatuses `json:"status" url:"status"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *IdentityProfileListItemVerificationsItem) GetCreatedAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.CreatedAt
}

func (i *IdentityProfileListItemVerificationsItem) GetID() string {
	if i == nil {
		return ""
	}
	return i.ID
}

func (i *IdentityProfileListItemVerificationsItem) GetLastErrorCode() *VerificationErrorCodes {
	if i == nil {
		return nil
	}
	return i.LastErrorCode
}

func (i *IdentityProfileListItemVerificationsItem) GetLastErrorReason() *string {
	if i == nil {
		return nil
	}
	return i.LastErrorReason
}

func (i *IdentityProfileListItemVerificationsItem) GetSessionURL() *string {
	if i == nil {
		return nil
	}
	return i.SessionURL
}

func (i *IdentityProfileListItemVerificationsItem) GetStatus() VerificationStatuses {
	if i == nil {
		return ""
	}
	return i.Status
}

func (i *IdentityProfileListItemVerificationsItem) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *IdentityProfileListItemVerificationsItem) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItemVerificationsItem) SetCreatedAt(createdAt time.Time) {
	i.CreatedAt = createdAt
	i.require(identityProfileListItemVerificationsItemFieldCreatedAt)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItemVerificationsItem) SetID(id string) {
	i.ID = id
	i.require(identityProfileListItemVerificationsItemFieldID)
}

// SetLastErrorCode sets the LastErrorCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItemVerificationsItem) SetLastErrorCode(lastErrorCode *VerificationErrorCodes) {
	i.LastErrorCode = lastErrorCode
	i.require(identityProfileListItemVerificationsItemFieldLastErrorCode)
}

// SetLastErrorReason sets the LastErrorReason field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItemVerificationsItem) SetLastErrorReason(lastErrorReason *string) {
	i.LastErrorReason = lastErrorReason
	i.require(identityProfileListItemVerificationsItemFieldLastErrorReason)
}

// SetSessionURL sets the SessionURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItemVerificationsItem) SetSessionURL(sessionURL *string) {
	i.SessionURL = sessionURL
	i.require(identityProfileListItemVerificationsItemFieldSessionURL)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileListItemVerificationsItem) SetStatus(status VerificationStatuses) {
	i.Status = status
	i.require(identityProfileListItemVerificationsItemFieldStatus)
}

func (i *IdentityProfileListItemVerificationsItem) UnmarshalJSON(data []byte) error {
	type embed IdentityProfileListItemVerificationsItem
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
	}{
		embed: embed(*i),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*i = IdentityProfileListItemVerificationsItem(unmarshaler.embed)
	i.CreatedAt = unmarshaler.CreatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *IdentityProfileListItemVerificationsItem) MarshalJSON() ([]byte, error) {
	type embed IdentityProfileListItemVerificationsItem
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
	}{
		embed:     embed(*i),
		CreatedAt: internal.NewDateTime(i.CreatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *IdentityProfileListItemVerificationsItem) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// Residential address reported by the identity provider. Present on `individual` profiles.
var (
	identityProfilePersonalAddressFieldCity       = big.NewInt(1 << 0)
	identityProfilePersonalAddressFieldCountry    = big.NewInt(1 << 1)
	identityProfilePersonalAddressFieldLine1      = big.NewInt(1 << 2)
	identityProfilePersonalAddressFieldLine2      = big.NewInt(1 << 3)
	identityProfilePersonalAddressFieldPostalCode = big.NewInt(1 << 4)
	identityProfilePersonalAddressFieldState      = big.NewInt(1 << 5)
)

type IdentityProfilePersonalAddress struct {
	// The city of the address.
	City *string `json:"city,omitempty" url:"city,omitempty"`
	// The country of the address.
	Country *string `json:"country,omitempty" url:"country,omitempty"`
	// The line 1 of the address.
	Line1 *string `json:"line1,omitempty" url:"line1,omitempty"`
	// The line 2 of the address.
	Line2 *string `json:"line2,omitempty" url:"line2,omitempty"`
	// The postal code of the address.
	PostalCode *string `json:"postal_code,omitempty" url:"postal_code,omitempty"`
	// The state of the address.
	State *string `json:"state,omitempty" url:"state,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *IdentityProfilePersonalAddress) GetCity() *string {
	if i == nil {
		return nil
	}
	return i.City
}

func (i *IdentityProfilePersonalAddress) GetCountry() *string {
	if i == nil {
		return nil
	}
	return i.Country
}

func (i *IdentityProfilePersonalAddress) GetLine1() *string {
	if i == nil {
		return nil
	}
	return i.Line1
}

func (i *IdentityProfilePersonalAddress) GetLine2() *string {
	if i == nil {
		return nil
	}
	return i.Line2
}

func (i *IdentityProfilePersonalAddress) GetPostalCode() *string {
	if i == nil {
		return nil
	}
	return i.PostalCode
}

func (i *IdentityProfilePersonalAddress) GetState() *string {
	if i == nil {
		return nil
	}
	return i.State
}

func (i *IdentityProfilePersonalAddress) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *IdentityProfilePersonalAddress) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetCity sets the City field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfilePersonalAddress) SetCity(city *string) {
	i.City = city
	i.require(identityProfilePersonalAddressFieldCity)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfilePersonalAddress) SetCountry(country *string) {
	i.Country = country
	i.require(identityProfilePersonalAddressFieldCountry)
}

// SetLine1 sets the Line1 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfilePersonalAddress) SetLine1(line1 *string) {
	i.Line1 = line1
	i.require(identityProfilePersonalAddressFieldLine1)
}

// SetLine2 sets the Line2 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfilePersonalAddress) SetLine2(line2 *string) {
	i.Line2 = line2
	i.require(identityProfilePersonalAddressFieldLine2)
}

// SetPostalCode sets the PostalCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfilePersonalAddress) SetPostalCode(postalCode *string) {
	i.PostalCode = postalCode
	i.require(identityProfilePersonalAddressFieldPostalCode)
}

// SetState sets the State field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfilePersonalAddress) SetState(state *string) {
	i.State = state
	i.require(identityProfilePersonalAddressFieldState)
}

func (i *IdentityProfilePersonalAddress) UnmarshalJSON(data []byte) error {
	type unmarshaler IdentityProfilePersonalAddress
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = IdentityProfilePersonalAddress(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *IdentityProfilePersonalAddress) MarshalJSON() ([]byte, error) {
	type embed IdentityProfilePersonalAddress
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *IdentityProfilePersonalAddress) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// Derived verification status for an identity profile.
type IdentityProfileStatuses string

const (
	IdentityProfileStatusesNotStarted     IdentityProfileStatuses = "not_started"
	IdentityProfileStatusesPending        IdentityProfileStatuses = "pending"
	IdentityProfileStatusesManualReview   IdentityProfileStatuses = "manual_review"
	IdentityProfileStatusesApproved       IdentityProfileStatuses = "approved"
	IdentityProfileStatusesRejected       IdentityProfileStatuses = "rejected"
	IdentityProfileStatusesActionRequired IdentityProfileStatuses = "action_required"
)

func NewIdentityProfileStatusesFromString(s string) (IdentityProfileStatuses, error) {
	switch s {
	case "not_started":
		return IdentityProfileStatusesNotStarted, nil
	case "pending":
		return IdentityProfileStatusesPending, nil
	case "manual_review":
		return IdentityProfileStatusesManualReview, nil
	case "approved":
		return IdentityProfileStatusesApproved, nil
	case "rejected":
		return IdentityProfileStatusesRejected, nil
	case "action_required":
		return IdentityProfileStatusesActionRequired, nil
	}
	var t IdentityProfileStatuses
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (i IdentityProfileStatuses) Ptr() *IdentityProfileStatuses {
	return &i
}

// An identity verification session used to confirm a person or entity's identity for payout account eligibility.
var (
	identityProfileVerificationsItemFieldCreatedAt       = big.NewInt(1 << 0)
	identityProfileVerificationsItemFieldID              = big.NewInt(1 << 1)
	identityProfileVerificationsItemFieldLastErrorCode   = big.NewInt(1 << 2)
	identityProfileVerificationsItemFieldLastErrorReason = big.NewInt(1 << 3)
	identityProfileVerificationsItemFieldSessionURL      = big.NewInt(1 << 4)
	identityProfileVerificationsItemFieldStatus          = big.NewInt(1 << 5)
)

type IdentityProfileVerificationsItem struct {
	// When the verification record was created.
	CreatedAt time.Time `json:"created_at" url:"created_at"`
	// The numeric id of the verification record.
	ID string `json:"id" url:"id"`
	// The most recent error code returned during verification. Null if no error has occurred.
	LastErrorCode *VerificationErrorCodes `json:"last_error_code,omitempty" url:"last_error_code,omitempty"`
	// A human-readable explanation of the most recent verification error. Null if no error has occurred.
	LastErrorReason *string `json:"last_error_reason,omitempty" url:"last_error_reason,omitempty"`
	// A URL the user can visit to complete the verification process. Null if the session does not require user interaction.
	SessionURL *string `json:"session_url,omitempty" url:"session_url,omitempty"`
	// The current status of this verification session.
	Status VerificationStatuses `json:"status" url:"status"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *IdentityProfileVerificationsItem) GetCreatedAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.CreatedAt
}

func (i *IdentityProfileVerificationsItem) GetID() string {
	if i == nil {
		return ""
	}
	return i.ID
}

func (i *IdentityProfileVerificationsItem) GetLastErrorCode() *VerificationErrorCodes {
	if i == nil {
		return nil
	}
	return i.LastErrorCode
}

func (i *IdentityProfileVerificationsItem) GetLastErrorReason() *string {
	if i == nil {
		return nil
	}
	return i.LastErrorReason
}

func (i *IdentityProfileVerificationsItem) GetSessionURL() *string {
	if i == nil {
		return nil
	}
	return i.SessionURL
}

func (i *IdentityProfileVerificationsItem) GetStatus() VerificationStatuses {
	if i == nil {
		return ""
	}
	return i.Status
}

func (i *IdentityProfileVerificationsItem) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *IdentityProfileVerificationsItem) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileVerificationsItem) SetCreatedAt(createdAt time.Time) {
	i.CreatedAt = createdAt
	i.require(identityProfileVerificationsItemFieldCreatedAt)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileVerificationsItem) SetID(id string) {
	i.ID = id
	i.require(identityProfileVerificationsItemFieldID)
}

// SetLastErrorCode sets the LastErrorCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileVerificationsItem) SetLastErrorCode(lastErrorCode *VerificationErrorCodes) {
	i.LastErrorCode = lastErrorCode
	i.require(identityProfileVerificationsItemFieldLastErrorCode)
}

// SetLastErrorReason sets the LastErrorReason field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileVerificationsItem) SetLastErrorReason(lastErrorReason *string) {
	i.LastErrorReason = lastErrorReason
	i.require(identityProfileVerificationsItemFieldLastErrorReason)
}

// SetSessionURL sets the SessionURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileVerificationsItem) SetSessionURL(sessionURL *string) {
	i.SessionURL = sessionURL
	i.require(identityProfileVerificationsItemFieldSessionURL)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IdentityProfileVerificationsItem) SetStatus(status VerificationStatuses) {
	i.Status = status
	i.require(identityProfileVerificationsItemFieldStatus)
}

func (i *IdentityProfileVerificationsItem) UnmarshalJSON(data []byte) error {
	type embed IdentityProfileVerificationsItem
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
	}{
		embed: embed(*i),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*i = IdentityProfileVerificationsItem(unmarshaler.embed)
	i.CreatedAt = unmarshaler.CreatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *IdentityProfileVerificationsItem) MarshalJSON() ([]byte, error) {
	type embed IdentityProfileVerificationsItem
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
	}{
		embed:     embed(*i),
		CreatedAt: internal.NewDateTime(i.CreatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *IdentityProfileVerificationsItem) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// The connection type for IdentityProfile.
var (
	listIdentityProfileResponseFieldData     = big.NewInt(1 << 0)
	listIdentityProfileResponseFieldPageInfo = big.NewInt(1 << 1)
)

type ListIdentityProfileResponse struct {
	// A list of nodes.
	Data []*IdentityProfileListItem `json:"data" url:"data"`
	// Information to aid in pagination.
	PageInfo *PageInfo `json:"page_info" url:"page_info"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListIdentityProfileResponse) GetData() []*IdentityProfileListItem {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListIdentityProfileResponse) GetPageInfo() *PageInfo {
	if l == nil {
		return nil
	}
	return l.PageInfo
}

func (l *ListIdentityProfileResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListIdentityProfileResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListIdentityProfileResponse) SetData(data []*IdentityProfileListItem) {
	l.Data = data
	l.require(listIdentityProfileResponseFieldData)
}

// SetPageInfo sets the PageInfo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListIdentityProfileResponse) SetPageInfo(pageInfo *PageInfo) {
	l.PageInfo = pageInfo
	l.require(listIdentityProfileResponseFieldPageInfo)
}

func (l *ListIdentityProfileResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListIdentityProfileResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListIdentityProfileResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListIdentityProfileResponse) MarshalJSON() ([]byte, error) {
	type embed ListIdentityProfileResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListIdentityProfileResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

// The connection type for Verification.
var (
	listVerificationsIdentityProfileResponseFieldData     = big.NewInt(1 << 0)
	listVerificationsIdentityProfileResponseFieldPageInfo = big.NewInt(1 << 1)
)

type ListVerificationsIdentityProfileResponse struct {
	// A list of nodes.
	Data []*ListVerificationsIdentityProfileResponseDataItem `json:"data" url:"data"`
	// Information to aid in pagination.
	PageInfo *PageInfo `json:"page_info" url:"page_info"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListVerificationsIdentityProfileResponse) GetData() []*ListVerificationsIdentityProfileResponseDataItem {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListVerificationsIdentityProfileResponse) GetPageInfo() *PageInfo {
	if l == nil {
		return nil
	}
	return l.PageInfo
}

func (l *ListVerificationsIdentityProfileResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListVerificationsIdentityProfileResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListVerificationsIdentityProfileResponse) SetData(data []*ListVerificationsIdentityProfileResponseDataItem) {
	l.Data = data
	l.require(listVerificationsIdentityProfileResponseFieldData)
}

// SetPageInfo sets the PageInfo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListVerificationsIdentityProfileResponse) SetPageInfo(pageInfo *PageInfo) {
	l.PageInfo = pageInfo
	l.require(listVerificationsIdentityProfileResponseFieldPageInfo)
}

func (l *ListVerificationsIdentityProfileResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListVerificationsIdentityProfileResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListVerificationsIdentityProfileResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListVerificationsIdentityProfileResponse) MarshalJSON() ([]byte, error) {
	type embed ListVerificationsIdentityProfileResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListVerificationsIdentityProfileResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

// An identity verification session used to confirm a person or entity's identity for payout account eligibility.
var (
	listVerificationsIdentityProfileResponseDataItemFieldCreatedAt       = big.NewInt(1 << 0)
	listVerificationsIdentityProfileResponseDataItemFieldID              = big.NewInt(1 << 1)
	listVerificationsIdentityProfileResponseDataItemFieldLastErrorCode   = big.NewInt(1 << 2)
	listVerificationsIdentityProfileResponseDataItemFieldLastErrorReason = big.NewInt(1 << 3)
	listVerificationsIdentityProfileResponseDataItemFieldSessionURL      = big.NewInt(1 << 4)
	listVerificationsIdentityProfileResponseDataItemFieldStatus          = big.NewInt(1 << 5)
)

type ListVerificationsIdentityProfileResponseDataItem struct {
	// When the verification record was created.
	CreatedAt time.Time `json:"created_at" url:"created_at"`
	// The numeric id of the verification record.
	ID string `json:"id" url:"id"`
	// The most recent error code returned during verification. Null if no error has occurred.
	LastErrorCode *VerificationErrorCodes `json:"last_error_code,omitempty" url:"last_error_code,omitempty"`
	// A human-readable explanation of the most recent verification error. Null if no error has occurred.
	LastErrorReason *string `json:"last_error_reason,omitempty" url:"last_error_reason,omitempty"`
	// A URL the user can visit to complete the verification process. Null if the session does not require user interaction.
	SessionURL *string `json:"session_url,omitempty" url:"session_url,omitempty"`
	// The current status of this verification session.
	Status VerificationStatuses `json:"status" url:"status"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListVerificationsIdentityProfileResponseDataItem) GetCreatedAt() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.CreatedAt
}

func (l *ListVerificationsIdentityProfileResponseDataItem) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListVerificationsIdentityProfileResponseDataItem) GetLastErrorCode() *VerificationErrorCodes {
	if l == nil {
		return nil
	}
	return l.LastErrorCode
}

func (l *ListVerificationsIdentityProfileResponseDataItem) GetLastErrorReason() *string {
	if l == nil {
		return nil
	}
	return l.LastErrorReason
}

func (l *ListVerificationsIdentityProfileResponseDataItem) GetSessionURL() *string {
	if l == nil {
		return nil
	}
	return l.SessionURL
}

func (l *ListVerificationsIdentityProfileResponseDataItem) GetStatus() VerificationStatuses {
	if l == nil {
		return ""
	}
	return l.Status
}

func (l *ListVerificationsIdentityProfileResponseDataItem) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListVerificationsIdentityProfileResponseDataItem) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListVerificationsIdentityProfileResponseDataItem) SetCreatedAt(createdAt time.Time) {
	l.CreatedAt = createdAt
	l.require(listVerificationsIdentityProfileResponseDataItemFieldCreatedAt)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListVerificationsIdentityProfileResponseDataItem) SetID(id string) {
	l.ID = id
	l.require(listVerificationsIdentityProfileResponseDataItemFieldID)
}

// SetLastErrorCode sets the LastErrorCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListVerificationsIdentityProfileResponseDataItem) SetLastErrorCode(lastErrorCode *VerificationErrorCodes) {
	l.LastErrorCode = lastErrorCode
	l.require(listVerificationsIdentityProfileResponseDataItemFieldLastErrorCode)
}

// SetLastErrorReason sets the LastErrorReason field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListVerificationsIdentityProfileResponseDataItem) SetLastErrorReason(lastErrorReason *string) {
	l.LastErrorReason = lastErrorReason
	l.require(listVerificationsIdentityProfileResponseDataItemFieldLastErrorReason)
}

// SetSessionURL sets the SessionURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListVerificationsIdentityProfileResponseDataItem) SetSessionURL(sessionURL *string) {
	l.SessionURL = sessionURL
	l.require(listVerificationsIdentityProfileResponseDataItemFieldSessionURL)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListVerificationsIdentityProfileResponseDataItem) SetStatus(status VerificationStatuses) {
	l.Status = status
	l.require(listVerificationsIdentityProfileResponseDataItemFieldStatus)
}

func (l *ListVerificationsIdentityProfileResponseDataItem) UnmarshalJSON(data []byte) error {
	type embed ListVerificationsIdentityProfileResponseDataItem
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
	}{
		embed: embed(*l),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*l = ListVerificationsIdentityProfileResponseDataItem(unmarshaler.embed)
	l.CreatedAt = unmarshaler.CreatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListVerificationsIdentityProfileResponseDataItem) MarshalJSON() ([]byte, error) {
	type embed ListVerificationsIdentityProfileResponseDataItem
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
	}{
		embed:     embed(*l),
		CreatedAt: internal.NewDateTime(l.CreatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListVerificationsIdentityProfileResponseDataItem) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	unlinkIdentityProfileRequestFieldID              = big.NewInt(1 << 0)
	unlinkIdentityProfileRequestFieldLedgerAccountID = big.NewInt(1 << 1)
)

type UnlinkIdentityProfileRequest struct {
	// The ID of the IdentityProfile to unlink.
	ID string `json:"-" url:"-"`
	// The ID of the LedgerAccount to unlink the identity profile from.
	LedgerAccountID string `json:"-" url:"ledger_account_id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UnlinkIdentityProfileRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnlinkIdentityProfileRequest) SetID(id string) {
	u.ID = id
	u.require(unlinkIdentityProfileRequestFieldID)
}

// SetLedgerAccountID sets the LedgerAccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnlinkIdentityProfileRequest) SetLedgerAccountID(ledgerAccountID string) {
	u.LedgerAccountID = ledgerAccountID
	u.require(unlinkIdentityProfileRequestFieldLedgerAccountID)
}
