// Code generated by Fern. DO NOT EDIT.

package whopsdk

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/whopio/whopsdk-go/internal"
	big "math/big"
	time "time"
)

var (
	leaderboardPartnersRequestFieldPeriod = big.NewInt(1 << 0)
)

type LeaderboardPartnersRequest struct {
	// Time window for the rankings. `day`, `month`, and `year` count earnings since the start of the current calendar day, month, or year; `last_30_days` counts earnings over the trailing 30 days; `all_time` ranks lifetime earnings.
	Period *LeaderboardPartnersRequestPeriod `json:"-" url:"period,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *LeaderboardPartnersRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetPeriod sets the Period field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardPartnersRequest) SetPeriod(period *LeaderboardPartnersRequestPeriod) {
	l.Period = period
	l.require(leaderboardPartnersRequestFieldPeriod)
}

var (
	referredUsersPartnersRequestFieldHasBusinesses        = big.NewInt(1 << 0)
	referredUsersPartnersRequestFieldHasEarningBusinesses = big.NewInt(1 << 1)
	referredUsersPartnersRequestFieldFirst                = big.NewInt(1 << 2)
	referredUsersPartnersRequestFieldAfter                = big.NewInt(1 << 3)
	referredUsersPartnersRequestFieldLast                 = big.NewInt(1 << 4)
	referredUsersPartnersRequestFieldBefore               = big.NewInt(1 << 5)
)

type ReferredUsersPartnersRequest struct {
	// When true, only referred users who brought at least one business onto Whop.
	HasBusinesses *bool `json:"-" url:"has_businesses,omitempty"`
	// When true, only referred users with at least one business that has generated earnings.
	HasEarningBusinesses *bool `json:"-" url:"has_earning_businesses,omitempty"`
	// Number of referred users to return from the start of the window.
	First *int `json:"-" url:"first,omitempty"`
	// Cursor to fetch the page after (from page_info.end_cursor).
	After *string `json:"-" url:"after,omitempty"`
	// Number of referred users to return from the end of the window.
	Last *int `json:"-" url:"last,omitempty"`
	// Cursor to fetch the page before (from page_info.start_cursor).
	Before *string `json:"-" url:"before,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *ReferredUsersPartnersRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetHasBusinesses sets the HasBusinesses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReferredUsersPartnersRequest) SetHasBusinesses(hasBusinesses *bool) {
	r.HasBusinesses = hasBusinesses
	r.require(referredUsersPartnersRequestFieldHasBusinesses)
}

// SetHasEarningBusinesses sets the HasEarningBusinesses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReferredUsersPartnersRequest) SetHasEarningBusinesses(hasEarningBusinesses *bool) {
	r.HasEarningBusinesses = hasEarningBusinesses
	r.require(referredUsersPartnersRequestFieldHasEarningBusinesses)
}

// SetFirst sets the First field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReferredUsersPartnersRequest) SetFirst(first *int) {
	r.First = first
	r.require(referredUsersPartnersRequestFieldFirst)
}

// SetAfter sets the After field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReferredUsersPartnersRequest) SetAfter(after *string) {
	r.After = after
	r.require(referredUsersPartnersRequestFieldAfter)
}

// SetLast sets the Last field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReferredUsersPartnersRequest) SetLast(last *int) {
	r.Last = last
	r.require(referredUsersPartnersRequestFieldLast)
}

// SetBefore sets the Before field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReferredUsersPartnersRequest) SetBefore(before *string) {
	r.Before = before
	r.require(referredUsersPartnersRequestFieldBefore)
}

var (
	createPartnersResponseFieldReferralLink         = big.NewInt(1 << 0)
	createPartnersResponseFieldWhopPartnerEnabledAt = big.NewInt(1 << 1)
)

type CreatePartnersResponse struct {
	// The caller's referral link — businesses that sign up through it are attributed to the caller.
	ReferralLink string `json:"referral_link" url:"referral_link"`
	// When the caller became a Whop partner.
	WhopPartnerEnabledAt time.Time `json:"whop_partner_enabled_at" url:"whop_partner_enabled_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreatePartnersResponse) GetReferralLink() string {
	if c == nil {
		return ""
	}
	return c.ReferralLink
}

func (c *CreatePartnersResponse) GetWhopPartnerEnabledAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.WhopPartnerEnabledAt
}

func (c *CreatePartnersResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreatePartnersResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetReferralLink sets the ReferralLink field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePartnersResponse) SetReferralLink(referralLink string) {
	c.ReferralLink = referralLink
	c.require(createPartnersResponseFieldReferralLink)
}

// SetWhopPartnerEnabledAt sets the WhopPartnerEnabledAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePartnersResponse) SetWhopPartnerEnabledAt(whopPartnerEnabledAt time.Time) {
	c.WhopPartnerEnabledAt = whopPartnerEnabledAt
	c.require(createPartnersResponseFieldWhopPartnerEnabledAt)
}

func (c *CreatePartnersResponse) UnmarshalJSON(data []byte) error {
	type embed CreatePartnersResponse
	var unmarshaler = struct {
		embed
		WhopPartnerEnabledAt *internal.DateTime `json:"whop_partner_enabled_at"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CreatePartnersResponse(unmarshaler.embed)
	c.WhopPartnerEnabledAt = unmarshaler.WhopPartnerEnabledAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreatePartnersResponse) MarshalJSON() ([]byte, error) {
	type embed CreatePartnersResponse
	var marshaler = struct {
		embed
		WhopPartnerEnabledAt *internal.DateTime `json:"whop_partner_enabled_at"`
	}{
		embed:                embed(*c),
		WhopPartnerEnabledAt: internal.NewDateTime(c.WhopPartnerEnabledAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreatePartnersResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type LeaderboardPartnersRequestPeriod string

const (
	LeaderboardPartnersRequestPeriodDay        LeaderboardPartnersRequestPeriod = "day"
	LeaderboardPartnersRequestPeriodMonth      LeaderboardPartnersRequestPeriod = "month"
	LeaderboardPartnersRequestPeriodYear       LeaderboardPartnersRequestPeriod = "year"
	LeaderboardPartnersRequestPeriodLast30Days LeaderboardPartnersRequestPeriod = "last_30_days"
	LeaderboardPartnersRequestPeriodAllTime    LeaderboardPartnersRequestPeriod = "all_time"
)

func NewLeaderboardPartnersRequestPeriodFromString(s string) (LeaderboardPartnersRequestPeriod, error) {
	switch s {
	case "day":
		return LeaderboardPartnersRequestPeriodDay, nil
	case "month":
		return LeaderboardPartnersRequestPeriodMonth, nil
	case "year":
		return LeaderboardPartnersRequestPeriodYear, nil
	case "last_30_days":
		return LeaderboardPartnersRequestPeriodLast30Days, nil
	case "all_time":
		return LeaderboardPartnersRequestPeriodAllTime, nil
	}
	var t LeaderboardPartnersRequestPeriod
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l LeaderboardPartnersRequestPeriod) Ptr() *LeaderboardPartnersRequestPeriod {
	return &l
}

var (
	leaderboardPartnersResponseFieldLeaders = big.NewInt(1 << 0)
	leaderboardPartnersResponseFieldMe      = big.NewInt(1 << 1)
)

type LeaderboardPartnersResponse struct {
	// The top referrers by total earnings, best first.
	Leaders []*LeaderboardPartnersResponseLeadersItem `json:"leaders" url:"leaders"`
	// The caller's own standing; null when the caller has no referral earnings.
	Me *LeaderboardPartnersResponseMe `json:"me,omitempty" url:"me,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *LeaderboardPartnersResponse) GetLeaders() []*LeaderboardPartnersResponseLeadersItem {
	if l == nil {
		return nil
	}
	return l.Leaders
}

func (l *LeaderboardPartnersResponse) GetMe() *LeaderboardPartnersResponseMe {
	if l == nil {
		return nil
	}
	return l.Me
}

func (l *LeaderboardPartnersResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *LeaderboardPartnersResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetLeaders sets the Leaders field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardPartnersResponse) SetLeaders(leaders []*LeaderboardPartnersResponseLeadersItem) {
	l.Leaders = leaders
	l.require(leaderboardPartnersResponseFieldLeaders)
}

// SetMe sets the Me field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardPartnersResponse) SetMe(me *LeaderboardPartnersResponseMe) {
	l.Me = me
	l.require(leaderboardPartnersResponseFieldMe)
}

func (l *LeaderboardPartnersResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler LeaderboardPartnersResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = LeaderboardPartnersResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *LeaderboardPartnersResponse) MarshalJSON() ([]byte, error) {
	type embed LeaderboardPartnersResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *LeaderboardPartnersResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	leaderboardPartnersResponseLeadersItemFieldFirstReferralStartedAt = big.NewInt(1 << 0)
	leaderboardPartnersResponseLeadersItemFieldRank                   = big.NewInt(1 << 1)
	leaderboardPartnersResponseLeadersItemFieldTotalEarningsUsd       = big.NewInt(1 << 2)
	leaderboardPartnersResponseLeadersItemFieldTotalVolumeUsd         = big.NewInt(1 << 3)
	leaderboardPartnersResponseLeadersItemFieldUser                   = big.NewInt(1 << 4)
)

type LeaderboardPartnersResponseLeadersItem struct {
	// When the referrer's earliest partner business became active.
	FirstReferralStartedAt time.Time `json:"first_referral_started_at" url:"first_referral_started_at"`
	// 1-based leaderboard position.
	Rank int `json:"rank" url:"rank"`
	// The referrer's pending + completed earnings across all referred businesses, in USD.
	TotalEarningsUsd string `json:"total_earnings_usd" url:"total_earnings_usd"`
	// Credited GMV across all the referrer's referred businesses, in USD.
	TotalVolumeUsd string `json:"total_volume_usd" url:"total_volume_usd"`
	// The ranked referrer. Identity fields (id, name, username, profile_picture) are returned only on the caller's own entry; other referrers expose coarse location only.
	User *LeaderboardPartnersResponseLeadersItemUser `json:"user,omitempty" url:"user,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *LeaderboardPartnersResponseLeadersItem) GetFirstReferralStartedAt() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.FirstReferralStartedAt
}

func (l *LeaderboardPartnersResponseLeadersItem) GetRank() int {
	if l == nil {
		return 0
	}
	return l.Rank
}

func (l *LeaderboardPartnersResponseLeadersItem) GetTotalEarningsUsd() string {
	if l == nil {
		return ""
	}
	return l.TotalEarningsUsd
}

func (l *LeaderboardPartnersResponseLeadersItem) GetTotalVolumeUsd() string {
	if l == nil {
		return ""
	}
	return l.TotalVolumeUsd
}

func (l *LeaderboardPartnersResponseLeadersItem) GetUser() *LeaderboardPartnersResponseLeadersItemUser {
	if l == nil {
		return nil
	}
	return l.User
}

func (l *LeaderboardPartnersResponseLeadersItem) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *LeaderboardPartnersResponseLeadersItem) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetFirstReferralStartedAt sets the FirstReferralStartedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardPartnersResponseLeadersItem) SetFirstReferralStartedAt(firstReferralStartedAt time.Time) {
	l.FirstReferralStartedAt = firstReferralStartedAt
	l.require(leaderboardPartnersResponseLeadersItemFieldFirstReferralStartedAt)
}

// SetRank sets the Rank field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardPartnersResponseLeadersItem) SetRank(rank int) {
	l.Rank = rank
	l.require(leaderboardPartnersResponseLeadersItemFieldRank)
}

// SetTotalEarningsUsd sets the TotalEarningsUsd field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardPartnersResponseLeadersItem) SetTotalEarningsUsd(totalEarningsUsd string) {
	l.TotalEarningsUsd = totalEarningsUsd
	l.require(leaderboardPartnersResponseLeadersItemFieldTotalEarningsUsd)
}

// SetTotalVolumeUsd sets the TotalVolumeUsd field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardPartnersResponseLeadersItem) SetTotalVolumeUsd(totalVolumeUsd string) {
	l.TotalVolumeUsd = totalVolumeUsd
	l.require(leaderboardPartnersResponseLeadersItemFieldTotalVolumeUsd)
}

// SetUser sets the User field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardPartnersResponseLeadersItem) SetUser(user *LeaderboardPartnersResponseLeadersItemUser) {
	l.User = user
	l.require(leaderboardPartnersResponseLeadersItemFieldUser)
}

func (l *LeaderboardPartnersResponseLeadersItem) UnmarshalJSON(data []byte) error {
	type embed LeaderboardPartnersResponseLeadersItem
	var unmarshaler = struct {
		embed
		FirstReferralStartedAt *internal.DateTime `json:"first_referral_started_at"`
	}{
		embed: embed(*l),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*l = LeaderboardPartnersResponseLeadersItem(unmarshaler.embed)
	l.FirstReferralStartedAt = unmarshaler.FirstReferralStartedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *LeaderboardPartnersResponseLeadersItem) MarshalJSON() ([]byte, error) {
	type embed LeaderboardPartnersResponseLeadersItem
	var marshaler = struct {
		embed
		FirstReferralStartedAt *internal.DateTime `json:"first_referral_started_at"`
	}{
		embed:                  embed(*l),
		FirstReferralStartedAt: internal.NewDateTime(l.FirstReferralStartedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *LeaderboardPartnersResponseLeadersItem) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

// The ranked referrer. Identity fields (id, name, username, profile_picture) are returned only on the caller's own entry; other referrers expose coarse location only.
var (
	leaderboardPartnersResponseLeadersItemUserFieldCity           = big.NewInt(1 << 0)
	leaderboardPartnersResponseLeadersItemUserFieldCountry        = big.NewInt(1 << 1)
	leaderboardPartnersResponseLeadersItemUserFieldID             = big.NewInt(1 << 2)
	leaderboardPartnersResponseLeadersItemUserFieldName           = big.NewInt(1 << 3)
	leaderboardPartnersResponseLeadersItemUserFieldProfilePicture = big.NewInt(1 << 4)
	leaderboardPartnersResponseLeadersItemUserFieldUsername       = big.NewInt(1 << 5)
)

type LeaderboardPartnersResponseLeadersItemUser struct {
	// The city where the referrer is located, derived from their IP address. Null if location sharing is disabled.
	City *string `json:"city,omitempty" url:"city,omitempty"`
	// The country where the referrer is located, derived from their IP address. Null if location sharing is disabled.
	Country *string `json:"country,omitempty" url:"country,omitempty"`
	// User ID, prefixed `user_`. Present only on the caller's own entry.
	ID *string `json:"id,omitempty" url:"id,omitempty"`
	// The user's display name. Present only on the caller's own entry.
	Name *string `json:"name,omitempty" url:"name,omitempty"`
	// The user's profile picture. Present only on the caller's own entry.
	ProfilePicture *LeaderboardPartnersResponseLeadersItemUserProfilePicture `json:"profile_picture,omitempty" url:"profile_picture,omitempty"`
	// The user's unique username. Present only on the caller's own entry.
	Username *string `json:"username,omitempty" url:"username,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *LeaderboardPartnersResponseLeadersItemUser) GetCity() *string {
	if l == nil {
		return nil
	}
	return l.City
}

func (l *LeaderboardPartnersResponseLeadersItemUser) GetCountry() *string {
	if l == nil {
		return nil
	}
	return l.Country
}

func (l *LeaderboardPartnersResponseLeadersItemUser) GetID() *string {
	if l == nil {
		return nil
	}
	return l.ID
}

func (l *LeaderboardPartnersResponseLeadersItemUser) GetName() *string {
	if l == nil {
		return nil
	}
	return l.Name
}

func (l *LeaderboardPartnersResponseLeadersItemUser) GetProfilePicture() *LeaderboardPartnersResponseLeadersItemUserProfilePicture {
	if l == nil {
		return nil
	}
	return l.ProfilePicture
}

func (l *LeaderboardPartnersResponseLeadersItemUser) GetUsername() *string {
	if l == nil {
		return nil
	}
	return l.Username
}

func (l *LeaderboardPartnersResponseLeadersItemUser) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *LeaderboardPartnersResponseLeadersItemUser) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetCity sets the City field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardPartnersResponseLeadersItemUser) SetCity(city *string) {
	l.City = city
	l.require(leaderboardPartnersResponseLeadersItemUserFieldCity)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardPartnersResponseLeadersItemUser) SetCountry(country *string) {
	l.Country = country
	l.require(leaderboardPartnersResponseLeadersItemUserFieldCountry)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardPartnersResponseLeadersItemUser) SetID(id *string) {
	l.ID = id
	l.require(leaderboardPartnersResponseLeadersItemUserFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardPartnersResponseLeadersItemUser) SetName(name *string) {
	l.Name = name
	l.require(leaderboardPartnersResponseLeadersItemUserFieldName)
}

// SetProfilePicture sets the ProfilePicture field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardPartnersResponseLeadersItemUser) SetProfilePicture(profilePicture *LeaderboardPartnersResponseLeadersItemUserProfilePicture) {
	l.ProfilePicture = profilePicture
	l.require(leaderboardPartnersResponseLeadersItemUserFieldProfilePicture)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardPartnersResponseLeadersItemUser) SetUsername(username *string) {
	l.Username = username
	l.require(leaderboardPartnersResponseLeadersItemUserFieldUsername)
}

func (l *LeaderboardPartnersResponseLeadersItemUser) UnmarshalJSON(data []byte) error {
	type unmarshaler LeaderboardPartnersResponseLeadersItemUser
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = LeaderboardPartnersResponseLeadersItemUser(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *LeaderboardPartnersResponseLeadersItemUser) MarshalJSON() ([]byte, error) {
	type embed LeaderboardPartnersResponseLeadersItemUser
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *LeaderboardPartnersResponseLeadersItemUser) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

// The user's profile picture. Present only on the caller's own entry.
var (
	leaderboardPartnersResponseLeadersItemUserProfilePictureFieldURL = big.NewInt(1 << 0)
)

type LeaderboardPartnersResponseLeadersItemUserProfilePicture struct {
	// The user's profile picture URL.
	URL string `json:"url" url:"url"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *LeaderboardPartnersResponseLeadersItemUserProfilePicture) GetURL() string {
	if l == nil {
		return ""
	}
	return l.URL
}

func (l *LeaderboardPartnersResponseLeadersItemUserProfilePicture) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *LeaderboardPartnersResponseLeadersItemUserProfilePicture) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardPartnersResponseLeadersItemUserProfilePicture) SetURL(url string) {
	l.URL = url
	l.require(leaderboardPartnersResponseLeadersItemUserProfilePictureFieldURL)
}

func (l *LeaderboardPartnersResponseLeadersItemUserProfilePicture) UnmarshalJSON(data []byte) error {
	type unmarshaler LeaderboardPartnersResponseLeadersItemUserProfilePicture
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = LeaderboardPartnersResponseLeadersItemUserProfilePicture(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *LeaderboardPartnersResponseLeadersItemUserProfilePicture) MarshalJSON() ([]byte, error) {
	type embed LeaderboardPartnersResponseLeadersItemUserProfilePicture
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *LeaderboardPartnersResponseLeadersItemUserProfilePicture) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

// The caller's own standing; null when the caller has no referral earnings.
var (
	leaderboardPartnersResponseMeFieldFirstReferralStartedAt = big.NewInt(1 << 0)
	leaderboardPartnersResponseMeFieldRank                   = big.NewInt(1 << 1)
	leaderboardPartnersResponseMeFieldTotalEarningsUsd       = big.NewInt(1 << 2)
	leaderboardPartnersResponseMeFieldTotalVolumeUsd         = big.NewInt(1 << 3)
	leaderboardPartnersResponseMeFieldUser                   = big.NewInt(1 << 4)
)

type LeaderboardPartnersResponseMe struct {
	// When the referrer's earliest partner business became active.
	FirstReferralStartedAt time.Time `json:"first_referral_started_at" url:"first_referral_started_at"`
	// 1-based leaderboard position.
	Rank int `json:"rank" url:"rank"`
	// The referrer's pending + completed earnings across all referred businesses, in USD.
	TotalEarningsUsd string `json:"total_earnings_usd" url:"total_earnings_usd"`
	// Credited GMV across all the referrer's referred businesses, in USD.
	TotalVolumeUsd string `json:"total_volume_usd" url:"total_volume_usd"`
	// The ranked referrer. Identity fields (id, name, username, profile_picture) are returned only on the caller's own entry; other referrers expose coarse location only.
	User *LeaderboardPartnersResponseMeUser `json:"user,omitempty" url:"user,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *LeaderboardPartnersResponseMe) GetFirstReferralStartedAt() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.FirstReferralStartedAt
}

func (l *LeaderboardPartnersResponseMe) GetRank() int {
	if l == nil {
		return 0
	}
	return l.Rank
}

func (l *LeaderboardPartnersResponseMe) GetTotalEarningsUsd() string {
	if l == nil {
		return ""
	}
	return l.TotalEarningsUsd
}

func (l *LeaderboardPartnersResponseMe) GetTotalVolumeUsd() string {
	if l == nil {
		return ""
	}
	return l.TotalVolumeUsd
}

func (l *LeaderboardPartnersResponseMe) GetUser() *LeaderboardPartnersResponseMeUser {
	if l == nil {
		return nil
	}
	return l.User
}

func (l *LeaderboardPartnersResponseMe) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *LeaderboardPartnersResponseMe) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetFirstReferralStartedAt sets the FirstReferralStartedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardPartnersResponseMe) SetFirstReferralStartedAt(firstReferralStartedAt time.Time) {
	l.FirstReferralStartedAt = firstReferralStartedAt
	l.require(leaderboardPartnersResponseMeFieldFirstReferralStartedAt)
}

// SetRank sets the Rank field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardPartnersResponseMe) SetRank(rank int) {
	l.Rank = rank
	l.require(leaderboardPartnersResponseMeFieldRank)
}

// SetTotalEarningsUsd sets the TotalEarningsUsd field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardPartnersResponseMe) SetTotalEarningsUsd(totalEarningsUsd string) {
	l.TotalEarningsUsd = totalEarningsUsd
	l.require(leaderboardPartnersResponseMeFieldTotalEarningsUsd)
}

// SetTotalVolumeUsd sets the TotalVolumeUsd field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardPartnersResponseMe) SetTotalVolumeUsd(totalVolumeUsd string) {
	l.TotalVolumeUsd = totalVolumeUsd
	l.require(leaderboardPartnersResponseMeFieldTotalVolumeUsd)
}

// SetUser sets the User field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardPartnersResponseMe) SetUser(user *LeaderboardPartnersResponseMeUser) {
	l.User = user
	l.require(leaderboardPartnersResponseMeFieldUser)
}

func (l *LeaderboardPartnersResponseMe) UnmarshalJSON(data []byte) error {
	type embed LeaderboardPartnersResponseMe
	var unmarshaler = struct {
		embed
		FirstReferralStartedAt *internal.DateTime `json:"first_referral_started_at"`
	}{
		embed: embed(*l),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*l = LeaderboardPartnersResponseMe(unmarshaler.embed)
	l.FirstReferralStartedAt = unmarshaler.FirstReferralStartedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *LeaderboardPartnersResponseMe) MarshalJSON() ([]byte, error) {
	type embed LeaderboardPartnersResponseMe
	var marshaler = struct {
		embed
		FirstReferralStartedAt *internal.DateTime `json:"first_referral_started_at"`
	}{
		embed:                  embed(*l),
		FirstReferralStartedAt: internal.NewDateTime(l.FirstReferralStartedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *LeaderboardPartnersResponseMe) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

// The ranked referrer. Identity fields (id, name, username, profile_picture) are returned only on the caller's own entry; other referrers expose coarse location only.
var (
	leaderboardPartnersResponseMeUserFieldCity           = big.NewInt(1 << 0)
	leaderboardPartnersResponseMeUserFieldCountry        = big.NewInt(1 << 1)
	leaderboardPartnersResponseMeUserFieldID             = big.NewInt(1 << 2)
	leaderboardPartnersResponseMeUserFieldName           = big.NewInt(1 << 3)
	leaderboardPartnersResponseMeUserFieldProfilePicture = big.NewInt(1 << 4)
	leaderboardPartnersResponseMeUserFieldUsername       = big.NewInt(1 << 5)
)

type LeaderboardPartnersResponseMeUser struct {
	// The city where the referrer is located, derived from their IP address. Null if location sharing is disabled.
	City *string `json:"city,omitempty" url:"city,omitempty"`
	// The country where the referrer is located, derived from their IP address. Null if location sharing is disabled.
	Country *string `json:"country,omitempty" url:"country,omitempty"`
	// User ID, prefixed `user_`. Present only on the caller's own entry.
	ID *string `json:"id,omitempty" url:"id,omitempty"`
	// The user's display name. Present only on the caller's own entry.
	Name *string `json:"name,omitempty" url:"name,omitempty"`
	// The user's profile picture. Present only on the caller's own entry.
	ProfilePicture *LeaderboardPartnersResponseMeUserProfilePicture `json:"profile_picture,omitempty" url:"profile_picture,omitempty"`
	// The user's unique username. Present only on the caller's own entry.
	Username *string `json:"username,omitempty" url:"username,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *LeaderboardPartnersResponseMeUser) GetCity() *string {
	if l == nil {
		return nil
	}
	return l.City
}

func (l *LeaderboardPartnersResponseMeUser) GetCountry() *string {
	if l == nil {
		return nil
	}
	return l.Country
}

func (l *LeaderboardPartnersResponseMeUser) GetID() *string {
	if l == nil {
		return nil
	}
	return l.ID
}

func (l *LeaderboardPartnersResponseMeUser) GetName() *string {
	if l == nil {
		return nil
	}
	return l.Name
}

func (l *LeaderboardPartnersResponseMeUser) GetProfilePicture() *LeaderboardPartnersResponseMeUserProfilePicture {
	if l == nil {
		return nil
	}
	return l.ProfilePicture
}

func (l *LeaderboardPartnersResponseMeUser) GetUsername() *string {
	if l == nil {
		return nil
	}
	return l.Username
}

func (l *LeaderboardPartnersResponseMeUser) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *LeaderboardPartnersResponseMeUser) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetCity sets the City field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardPartnersResponseMeUser) SetCity(city *string) {
	l.City = city
	l.require(leaderboardPartnersResponseMeUserFieldCity)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardPartnersResponseMeUser) SetCountry(country *string) {
	l.Country = country
	l.require(leaderboardPartnersResponseMeUserFieldCountry)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardPartnersResponseMeUser) SetID(id *string) {
	l.ID = id
	l.require(leaderboardPartnersResponseMeUserFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardPartnersResponseMeUser) SetName(name *string) {
	l.Name = name
	l.require(leaderboardPartnersResponseMeUserFieldName)
}

// SetProfilePicture sets the ProfilePicture field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardPartnersResponseMeUser) SetProfilePicture(profilePicture *LeaderboardPartnersResponseMeUserProfilePicture) {
	l.ProfilePicture = profilePicture
	l.require(leaderboardPartnersResponseMeUserFieldProfilePicture)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardPartnersResponseMeUser) SetUsername(username *string) {
	l.Username = username
	l.require(leaderboardPartnersResponseMeUserFieldUsername)
}

func (l *LeaderboardPartnersResponseMeUser) UnmarshalJSON(data []byte) error {
	type unmarshaler LeaderboardPartnersResponseMeUser
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = LeaderboardPartnersResponseMeUser(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *LeaderboardPartnersResponseMeUser) MarshalJSON() ([]byte, error) {
	type embed LeaderboardPartnersResponseMeUser
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *LeaderboardPartnersResponseMeUser) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

// The user's profile picture. Present only on the caller's own entry.
var (
	leaderboardPartnersResponseMeUserProfilePictureFieldURL = big.NewInt(1 << 0)
)

type LeaderboardPartnersResponseMeUserProfilePicture struct {
	// The user's profile picture URL.
	URL string `json:"url" url:"url"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *LeaderboardPartnersResponseMeUserProfilePicture) GetURL() string {
	if l == nil {
		return ""
	}
	return l.URL
}

func (l *LeaderboardPartnersResponseMeUserProfilePicture) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *LeaderboardPartnersResponseMeUserProfilePicture) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardPartnersResponseMeUserProfilePicture) SetURL(url string) {
	l.URL = url
	l.require(leaderboardPartnersResponseMeUserProfilePictureFieldURL)
}

func (l *LeaderboardPartnersResponseMeUserProfilePicture) UnmarshalJSON(data []byte) error {
	type unmarshaler LeaderboardPartnersResponseMeUserProfilePicture
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = LeaderboardPartnersResponseMeUserProfilePicture(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *LeaderboardPartnersResponseMeUserProfilePicture) MarshalJSON() ([]byte, error) {
	type embed LeaderboardPartnersResponseMeUserProfilePicture
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *LeaderboardPartnersResponseMeUserProfilePicture) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	referredUsersPartnersResponseFieldData     = big.NewInt(1 << 0)
	referredUsersPartnersResponseFieldPageInfo = big.NewInt(1 << 1)
)

type ReferredUsersPartnersResponse struct {
	Data     []*ReferredUsersPartnersResponseDataItem `json:"data" url:"data"`
	PageInfo *ReferredUsersPartnersResponsePageInfo   `json:"page_info" url:"page_info"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ReferredUsersPartnersResponse) GetData() []*ReferredUsersPartnersResponseDataItem {
	if r == nil {
		return nil
	}
	return r.Data
}

func (r *ReferredUsersPartnersResponse) GetPageInfo() *ReferredUsersPartnersResponsePageInfo {
	if r == nil {
		return nil
	}
	return r.PageInfo
}

func (r *ReferredUsersPartnersResponse) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *ReferredUsersPartnersResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReferredUsersPartnersResponse) SetData(data []*ReferredUsersPartnersResponseDataItem) {
	r.Data = data
	r.require(referredUsersPartnersResponseFieldData)
}

// SetPageInfo sets the PageInfo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReferredUsersPartnersResponse) SetPageInfo(pageInfo *ReferredUsersPartnersResponsePageInfo) {
	r.PageInfo = pageInfo
	r.require(referredUsersPartnersResponseFieldPageInfo)
}

func (r *ReferredUsersPartnersResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ReferredUsersPartnersResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ReferredUsersPartnersResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ReferredUsersPartnersResponse) MarshalJSON() ([]byte, error) {
	type embed ReferredUsersPartnersResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ReferredUsersPartnersResponse) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	referredUsersPartnersResponseDataItemFieldTotalEarningsUsd = big.NewInt(1 << 0)
	referredUsersPartnersResponseDataItemFieldTotalVolumeUsd   = big.NewInt(1 << 1)
	referredUsersPartnersResponseDataItemFieldUser             = big.NewInt(1 << 2)
)

type ReferredUsersPartnersResponseDataItem struct {
	TotalEarningsUsd string                                     `json:"total_earnings_usd" url:"total_earnings_usd"`
	TotalVolumeUsd   string                                     `json:"total_volume_usd" url:"total_volume_usd"`
	User             *ReferredUsersPartnersResponseDataItemUser `json:"user" url:"user"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ReferredUsersPartnersResponseDataItem) GetTotalEarningsUsd() string {
	if r == nil {
		return ""
	}
	return r.TotalEarningsUsd
}

func (r *ReferredUsersPartnersResponseDataItem) GetTotalVolumeUsd() string {
	if r == nil {
		return ""
	}
	return r.TotalVolumeUsd
}

func (r *ReferredUsersPartnersResponseDataItem) GetUser() *ReferredUsersPartnersResponseDataItemUser {
	if r == nil {
		return nil
	}
	return r.User
}

func (r *ReferredUsersPartnersResponseDataItem) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *ReferredUsersPartnersResponseDataItem) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetTotalEarningsUsd sets the TotalEarningsUsd field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReferredUsersPartnersResponseDataItem) SetTotalEarningsUsd(totalEarningsUsd string) {
	r.TotalEarningsUsd = totalEarningsUsd
	r.require(referredUsersPartnersResponseDataItemFieldTotalEarningsUsd)
}

// SetTotalVolumeUsd sets the TotalVolumeUsd field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReferredUsersPartnersResponseDataItem) SetTotalVolumeUsd(totalVolumeUsd string) {
	r.TotalVolumeUsd = totalVolumeUsd
	r.require(referredUsersPartnersResponseDataItemFieldTotalVolumeUsd)
}

// SetUser sets the User field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReferredUsersPartnersResponseDataItem) SetUser(user *ReferredUsersPartnersResponseDataItemUser) {
	r.User = user
	r.require(referredUsersPartnersResponseDataItemFieldUser)
}

func (r *ReferredUsersPartnersResponseDataItem) UnmarshalJSON(data []byte) error {
	type unmarshaler ReferredUsersPartnersResponseDataItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ReferredUsersPartnersResponseDataItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ReferredUsersPartnersResponseDataItem) MarshalJSON() ([]byte, error) {
	type embed ReferredUsersPartnersResponseDataItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ReferredUsersPartnersResponseDataItem) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	referredUsersPartnersResponseDataItemUserFieldCity           = big.NewInt(1 << 0)
	referredUsersPartnersResponseDataItemUserFieldCountry        = big.NewInt(1 << 1)
	referredUsersPartnersResponseDataItemUserFieldID             = big.NewInt(1 << 2)
	referredUsersPartnersResponseDataItemUserFieldName           = big.NewInt(1 << 3)
	referredUsersPartnersResponseDataItemUserFieldProfilePicture = big.NewInt(1 << 4)
	referredUsersPartnersResponseDataItemUserFieldUsername       = big.NewInt(1 << 5)
)

type ReferredUsersPartnersResponseDataItemUser struct {
	City           *string                                                  `json:"city,omitempty" url:"city,omitempty"`
	Country        *string                                                  `json:"country,omitempty" url:"country,omitempty"`
	ID             string                                                   `json:"id" url:"id"`
	Name           *string                                                  `json:"name,omitempty" url:"name,omitempty"`
	ProfilePicture *ReferredUsersPartnersResponseDataItemUserProfilePicture `json:"profile_picture,omitempty" url:"profile_picture,omitempty"`
	Username       string                                                   `json:"username" url:"username"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ReferredUsersPartnersResponseDataItemUser) GetCity() *string {
	if r == nil {
		return nil
	}
	return r.City
}

func (r *ReferredUsersPartnersResponseDataItemUser) GetCountry() *string {
	if r == nil {
		return nil
	}
	return r.Country
}

func (r *ReferredUsersPartnersResponseDataItemUser) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *ReferredUsersPartnersResponseDataItemUser) GetName() *string {
	if r == nil {
		return nil
	}
	return r.Name
}

func (r *ReferredUsersPartnersResponseDataItemUser) GetProfilePicture() *ReferredUsersPartnersResponseDataItemUserProfilePicture {
	if r == nil {
		return nil
	}
	return r.ProfilePicture
}

func (r *ReferredUsersPartnersResponseDataItemUser) GetUsername() string {
	if r == nil {
		return ""
	}
	return r.Username
}

func (r *ReferredUsersPartnersResponseDataItemUser) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *ReferredUsersPartnersResponseDataItemUser) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetCity sets the City field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReferredUsersPartnersResponseDataItemUser) SetCity(city *string) {
	r.City = city
	r.require(referredUsersPartnersResponseDataItemUserFieldCity)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReferredUsersPartnersResponseDataItemUser) SetCountry(country *string) {
	r.Country = country
	r.require(referredUsersPartnersResponseDataItemUserFieldCountry)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReferredUsersPartnersResponseDataItemUser) SetID(id string) {
	r.ID = id
	r.require(referredUsersPartnersResponseDataItemUserFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReferredUsersPartnersResponseDataItemUser) SetName(name *string) {
	r.Name = name
	r.require(referredUsersPartnersResponseDataItemUserFieldName)
}

// SetProfilePicture sets the ProfilePicture field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReferredUsersPartnersResponseDataItemUser) SetProfilePicture(profilePicture *ReferredUsersPartnersResponseDataItemUserProfilePicture) {
	r.ProfilePicture = profilePicture
	r.require(referredUsersPartnersResponseDataItemUserFieldProfilePicture)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReferredUsersPartnersResponseDataItemUser) SetUsername(username string) {
	r.Username = username
	r.require(referredUsersPartnersResponseDataItemUserFieldUsername)
}

func (r *ReferredUsersPartnersResponseDataItemUser) UnmarshalJSON(data []byte) error {
	type unmarshaler ReferredUsersPartnersResponseDataItemUser
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ReferredUsersPartnersResponseDataItemUser(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ReferredUsersPartnersResponseDataItemUser) MarshalJSON() ([]byte, error) {
	type embed ReferredUsersPartnersResponseDataItemUser
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ReferredUsersPartnersResponseDataItemUser) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	referredUsersPartnersResponseDataItemUserProfilePictureFieldURL = big.NewInt(1 << 0)
)

type ReferredUsersPartnersResponseDataItemUserProfilePicture struct {
	URL *string `json:"url,omitempty" url:"url,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ReferredUsersPartnersResponseDataItemUserProfilePicture) GetURL() *string {
	if r == nil {
		return nil
	}
	return r.URL
}

func (r *ReferredUsersPartnersResponseDataItemUserProfilePicture) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *ReferredUsersPartnersResponseDataItemUserProfilePicture) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReferredUsersPartnersResponseDataItemUserProfilePicture) SetURL(url *string) {
	r.URL = url
	r.require(referredUsersPartnersResponseDataItemUserProfilePictureFieldURL)
}

func (r *ReferredUsersPartnersResponseDataItemUserProfilePicture) UnmarshalJSON(data []byte) error {
	type unmarshaler ReferredUsersPartnersResponseDataItemUserProfilePicture
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ReferredUsersPartnersResponseDataItemUserProfilePicture(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ReferredUsersPartnersResponseDataItemUserProfilePicture) MarshalJSON() ([]byte, error) {
	type embed ReferredUsersPartnersResponseDataItemUserProfilePicture
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ReferredUsersPartnersResponseDataItemUserProfilePicture) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	referredUsersPartnersResponsePageInfoFieldEndCursor       = big.NewInt(1 << 0)
	referredUsersPartnersResponsePageInfoFieldHasNextPage     = big.NewInt(1 << 1)
	referredUsersPartnersResponsePageInfoFieldHasPreviousPage = big.NewInt(1 << 2)
	referredUsersPartnersResponsePageInfoFieldStartCursor     = big.NewInt(1 << 3)
)

type ReferredUsersPartnersResponsePageInfo struct {
	EndCursor       *string `json:"end_cursor,omitempty" url:"end_cursor,omitempty"`
	HasNextPage     bool    `json:"has_next_page" url:"has_next_page"`
	HasPreviousPage bool    `json:"has_previous_page" url:"has_previous_page"`
	StartCursor     *string `json:"start_cursor,omitempty" url:"start_cursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ReferredUsersPartnersResponsePageInfo) GetEndCursor() *string {
	if r == nil {
		return nil
	}
	return r.EndCursor
}

func (r *ReferredUsersPartnersResponsePageInfo) GetHasNextPage() bool {
	if r == nil {
		return false
	}
	return r.HasNextPage
}

func (r *ReferredUsersPartnersResponsePageInfo) GetHasPreviousPage() bool {
	if r == nil {
		return false
	}
	return r.HasPreviousPage
}

func (r *ReferredUsersPartnersResponsePageInfo) GetStartCursor() *string {
	if r == nil {
		return nil
	}
	return r.StartCursor
}

func (r *ReferredUsersPartnersResponsePageInfo) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *ReferredUsersPartnersResponsePageInfo) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetEndCursor sets the EndCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReferredUsersPartnersResponsePageInfo) SetEndCursor(endCursor *string) {
	r.EndCursor = endCursor
	r.require(referredUsersPartnersResponsePageInfoFieldEndCursor)
}

// SetHasNextPage sets the HasNextPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReferredUsersPartnersResponsePageInfo) SetHasNextPage(hasNextPage bool) {
	r.HasNextPage = hasNextPage
	r.require(referredUsersPartnersResponsePageInfoFieldHasNextPage)
}

// SetHasPreviousPage sets the HasPreviousPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReferredUsersPartnersResponsePageInfo) SetHasPreviousPage(hasPreviousPage bool) {
	r.HasPreviousPage = hasPreviousPage
	r.require(referredUsersPartnersResponsePageInfoFieldHasPreviousPage)
}

// SetStartCursor sets the StartCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReferredUsersPartnersResponsePageInfo) SetStartCursor(startCursor *string) {
	r.StartCursor = startCursor
	r.require(referredUsersPartnersResponsePageInfoFieldStartCursor)
}

func (r *ReferredUsersPartnersResponsePageInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler ReferredUsersPartnersResponsePageInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ReferredUsersPartnersResponsePageInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ReferredUsersPartnersResponsePageInfo) MarshalJSON() ([]byte, error) {
	type embed ReferredUsersPartnersResponsePageInfo
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ReferredUsersPartnersResponsePageInfo) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}
