// Code generated by Fern. DO NOT EDIT.

// A Checkout Session is a server-priced offer for one plan: item, total, currency, and an expiry.
//
// Use the Checkout Sessions API to open a session, poll the quote, collect buyer requirements, and confirm payment.
package checkoutsessions
