// Code generated by Fern. DO NOT EDIT.

package payments

import (
	context "context"
	http "net/http"

	whopsdk "github.com/whopio/whopsdk-go"
	core "github.com/whopio/whopsdk-go/core"
	internal "github.com/whopio/whopsdk-go/internal"
	option "github.com/whopio/whopsdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.APIVersionDate == nil {
		apiVersionDateDefault := "2026-09-02-1"
		options.APIVersionDate = &apiVersionDateDefault
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Lists payments, newest first. Without filters this is every payment the caller can read: a company credential's own account, or for a user every account they can read payments for. Filters narrow by account, buyer, product, plan, membership, status, billing reason, currency, and creation window. Filtering by `billing_reason=subscription_cycle` also matches renewals recorded as `subscription_update`. `settlement_time_at` is null on list rows — retrieve the payment for it.
//
// Example:
//
//	request := &whopsdk.ListPaymentsRequest{}
//	client.Payments.List(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) List(
	ctx context.Context,
	request *whopsdk.ListPaymentsRequest,
	opts ...option.RequestOption,
) (*core.Page[*string, *whopsdk.Payment, *whopsdk.ListPaymentsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://api.whop.com/api/v1",
	)
	endpointURL := baseURL + "/payments"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	prepareCall := func(pageRequest *core.PageRequest[*string]) *internal.CallParams {
		if pageRequest.Cursor != nil {
			queryParams.Set("after", *pageRequest.Cursor)
		}
		nextURL := endpointURL
		if len(queryParams) > 0 {
			nextURL += "?" + queryParams.Encode()
		}
		return &internal.CallParams{
			URL:             nextURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        pageRequest.Response,
			ErrorDecoder:    internal.NewErrorDecoder(whopsdk.ErrorCodes),
		}
	}
	readPageResponse := func(response *whopsdk.ListPaymentsResponse) *core.PageResponse[*string, *whopsdk.Payment, *whopsdk.ListPaymentsResponse] {
		var zeroValue *string
		var next *string
		if response.PageInfo != nil {
			next = response.PageInfo.EndCursor
		}
		results := response.GetData()
		return &core.PageResponse[*string, *whopsdk.Payment, *whopsdk.ListPaymentsResponse]{
			Results:  results,
			Response: response,
			Next:     next,
			Done:     next == zeroValue || *next == "",
		}
	}
	pager := internal.NewCursorPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, request.After)
}

// Charges a buyer for a plan. Pass a payment method already on file (`member_id` and `payment_method_id`), or a `confirmation_token` describing a method the buyer just supplied. Collection runs in the background: the response is the payment as created, not its outcome — poll Retrieve status for how far it has got and, for a confirmation-token payment, what the buyer must still do. `plan_id` names the plan to charge for.
//
// Example:
//
//	request := &whopsdk.CreatePaymentsRequest{
//	    AccountID: "biz_xxxxxxxxxxxxxx",
//	    PlanID: "plan_xxxxxxxxxxxxxx",
//	}
//	client.Payments.Create(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Create(
	ctx context.Context,
	request *whopsdk.CreatePaymentsRequest,
	opts ...option.RequestOption,
) (*whopsdk.Payment, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns one payment. Related records are ids — resolve a plan, membership, member or shipment on its own endpoint, and list this payment's refunds, disputes or Resolution Center cases with `?payment_id=`.
//
// Example:
//
//	request := &whopsdk.RetrievePaymentsRequest{
//	    ID: "id",
//	}
//	client.Payments.Retrieve(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Retrieve(
	ctx context.Context,
	request *whopsdk.RetrievePaymentsRequest,
	opts ...option.RequestOption,
) (*whopsdk.Payment, error) {
	response, err := c.WithRawResponse.Retrieve(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Captures the full amount of a card payment created with `capture: false`. The payment must still be in `requires_capture` before `capture_expires_at`. Partial capture, multiple captures, capturing more than the authorized amount, and tips are not supported.
//
// Example:
//
//	request := &whopsdk.CapturePaymentsRequest{
//	    ID: "id",
//	}
//	client.Payments.Capture(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Capture(
	ctx context.Context,
	request *whopsdk.CapturePaymentsRequest,
	opts ...option.RequestOption,
) (*whopsdk.PaymentStatus, error) {
	response, err := c.WithRawResponse.Capture(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns the fee breakdown of one payment — Whop's fee, processing, affiliate and other lines — each in the currency it was collected in and converted to the payment's settlement currency. The list is complete in one page.
//
// Example:
//
//	request := &whopsdk.ListFeesPaymentsRequest{
//	    ID: "id",
//	}
//	client.Payments.ListFees(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListFees(
	ctx context.Context,
	request *whopsdk.ListFeesPaymentsRequest,
	opts ...option.RequestOption,
) (*whopsdk.ListFeesPaymentsResponse, error) {
	response, err := c.WithRawResponse.ListFees(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Issues a full or partial refund for a payment. The refund is processed through the original payment processor and the membership status is updated accordingly.
//
// Example:
//
//	request := &whopsdk.RefundPaymentsRequest{
//	    ID: "id",
//	}
//	client.Payments.Refund(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Refund(
	ctx context.Context,
	request *whopsdk.RefundPaymentsRequest,
	opts ...option.RequestOption,
) (*whopsdk.Payment, error) {
	response, err := c.WithRawResponse.Refund(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retries a failed or pending payment. This re-attempts the charge using the original payment method and plan details.
//
// Example:
//
//	request := &whopsdk.RetryPaymentsRequest{
//	    ID: "id",
//	}
//	client.Payments.Retry(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Retry(
	ctx context.Context,
	request *whopsdk.RetryPaymentsRequest,
	opts ...option.RequestOption,
) (*whopsdk.Payment, error) {
	response, err := c.WithRawResponse.Retry(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Voids a payment that has not yet been settled. Voiding cancels the payment before it is captured by the payment processor.
//
// Example:
//
//	request := &whopsdk.VoidPaymentsRequest{
//	    ID: "id",
//	}
//	client.Payments.Void(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Void(
	ctx context.Context,
	request *whopsdk.VoidPaymentsRequest,
	opts ...option.RequestOption,
) (*whopsdk.Payment, error) {
	response, err := c.WithRawResponse.Void(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Changes where the buyer lands after completing an off-site step, up until they return. Accepts either a secret key or the payment's own `client_secret`, so the surface that knows the final destination can set it.
//
// Example:
//
//	request := &whopsdk.UpdateReturnURLPaymentsRequest{
//	    PaymentID: "payment_id",
//	    ReturnURL: "https://shinetime.example/checkout/thanks",
//	}
//	client.Payments.UpdateReturnURL(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) UpdateReturnURL(
	ctx context.Context,
	request *whopsdk.UpdateReturnURLPaymentsRequest,
	opts ...option.RequestOption,
) (*whopsdk.PaymentStatus, error) {
	response, err := c.WithRawResponse.UpdateReturnURL(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieves how far a payment has got and what the buyer must do next, if anything. A payment is collected in the background, so poll this rather than reading the create response. Accepts either a secret key or the payment's own `client_secret`, so the surface collecting the payment can poll it directly.
//
// Example:
//
//	request := &whopsdk.RetrieveStatusPaymentsRequest{
//	    PaymentID: "payment_id",
//	}
//	client.Payments.RetrieveStatus(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) RetrieveStatus(
	ctx context.Context,
	request *whopsdk.RetrieveStatusPaymentsRequest,
	opts ...option.RequestOption,
) (*whopsdk.PaymentStatus, error) {
	response, err := c.WithRawResponse.RetrieveStatus(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
