// Code generated by Fern. DO NOT EDIT.

// Join a free plan's waitlist, read or cancel your own signups, and manage signups for accounts you are authorized to operate.
// Joining does not grant membership or charge a payment method. Seller approval runs asynchronously and can charge a saved payment method for a paid plan.
package waitlistentries
