// Code generated by Fern. DO NOT EDIT.

package cardtransactions

import (
	context "context"
	http "net/http"

	whopsdk "github.com/whopio/whopsdk-go"
	core "github.com/whopio/whopsdk-go/core"
	internal "github.com/whopio/whopsdk-go/internal"
	option "github.com/whopio/whopsdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.APIVersionDate == nil {
		apiVersionDateDefault := "2026-09-02-1"
		options.APIVersionDate = &apiVersionDateDefault
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Lists an account's card transactions, newest first. Defaults to the account the credential belongs to. Covers every card the owner has ever had, including canceled cards and spend that predates a re-application, and team members only see transactions on the cards assigned to them. Pass `transaction_ids` to fetch specific transactions instead of paging for them.
//
// Example:
//
//	request := &whopsdk.ListCardTransactionsRequest{
//	    TransactionIDs: []*string{
//	        whopsdk.String(
//	            "citx_xxxxxxxxxxxxxx",
//	        ),
//	    },
//	    CardID: []*string{
//	        whopsdk.String(
//	            "icrd_xxxxxxxxxxxxxx",
//	        ),
//	    },
//	    CardholderID: []*string{
//	        whopsdk.String(
//	            "user_xxxxxxxxxxxxxx",
//	        ),
//	    },
//	}
//	client.CardTransactions.List(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) List(
	ctx context.Context,
	request *whopsdk.ListCardTransactionsRequest,
	opts ...option.RequestOption,
) (*core.Page[*string, *whopsdk.CardTransaction, *whopsdk.ListCardTransactionsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://api.whop.com/api/v1",
	)
	endpointURL := baseURL + "/card_transactions"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	prepareCall := func(pageRequest *core.PageRequest[*string]) *internal.CallParams {
		if pageRequest.Cursor != nil {
			queryParams.Set("after", *pageRequest.Cursor)
		}
		nextURL := endpointURL
		if len(queryParams) > 0 {
			nextURL += "?" + queryParams.Encode()
		}
		return &internal.CallParams{
			URL:             nextURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        pageRequest.Response,
			ErrorDecoder:    internal.NewErrorDecoder(whopsdk.ErrorCodes),
		}
	}
	readPageResponse := func(response *whopsdk.ListCardTransactionsResponse) *core.PageResponse[*string, *whopsdk.CardTransaction, *whopsdk.ListCardTransactionsResponse] {
		var zeroValue *string
		var next *string
		if response.PageInfo != nil {
			next = response.PageInfo.EndCursor
		}
		results := response.GetData()
		return &core.PageResponse[*string, *whopsdk.CardTransaction, *whopsdk.ListCardTransactionsResponse]{
			Results:  results,
			Response: response,
			Next:     next,
			Done:     next == zeroValue || *next == "",
		}
	}
	pager := internal.NewCursorPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, request.After)
}

// Fetches a single card transaction by its `citx_` identifier. The owner defaults to the account the credential belongs to.
//
// Example:
//
//	request := &whopsdk.RetrieveCardTransactionsRequest{
//	    ID: "id",
//	}
//	client.CardTransactions.Retrieve(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Retrieve(
	ctx context.Context,
	request *whopsdk.RetrieveCardTransactionsRequest,
	opts ...option.RequestOption,
) (*whopsdk.CardTransaction, error) {
	response, err := c.WithRawResponse.Retrieve(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
