// Code generated by Fern. DO NOT EDIT.

package cards

import (
	context "context"

	whopsdk "github.com/whopio/whopsdk-go"
	core "github.com/whopio/whopsdk-go/core"
	internal "github.com/whopio/whopsdk-go/internal"
	option "github.com/whopio/whopsdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.APIVersionDate == nil {
		apiVersionDateDefault := "2026-08-25-1"
		options.APIVersionDate = &apiVersionDateDefault
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Lists the Whop cards of an account or user, including ones still being set up. Team members only see the cards assigned to them.
//
// Example:
//
//	request := &whopsdk.ListCardsRequest{}
//	client.Cards.List(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) List(
	ctx context.Context,
	request *whopsdk.ListCardsRequest,
	opts ...option.RequestOption,
) (*whopsdk.ListCardsResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Issue a virtual card, or apply for card issuing.
//
// Example:
//
//	request := &whopsdk.CreateCardsRequest{}
//	client.Cards.Create(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Create(
	ctx context.Context,
	request *whopsdk.CreateCardsRequest,
	opts ...option.RequestOption,
) (*whopsdk.CreateCardsResponse, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve a single card.
//
// Example:
//
//	request := &whopsdk.RetrieveCardsRequest{
//	    ID: "id",
//	}
//	client.Cards.Retrieve(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Retrieve(
	ctx context.Context,
	request *whopsdk.RetrieveCardsRequest,
	opts ...option.RequestOption,
) (*whopsdk.RetrieveCardsResponse, error) {
	response, err := c.WithRawResponse.Retrieve(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Update, freeze, or cancel a card. Updating the card's name, billing address, or limits requires both `payout:account:update` and `company:balance:read`; a card's assigned holder may update their own card's pin and frozen state with any user token.
//
// Example:
//
//	request := &whopsdk.UpdateCardsRequest{
//	    ID: "id",
//	}
//	client.Cards.Update(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Update(
	ctx context.Context,
	request *whopsdk.UpdateCardsRequest,
	opts ...option.RequestOption,
) (*whopsdk.UpdateCardsResponse, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
