// Code generated by Fern. DO NOT EDIT.

package feedbacksubmissions

import (
	context "context"

	whopsdk "github.com/whopio/whopsdk-go/v2"
	core "github.com/whopio/whopsdk-go/v2/core"
	internal "github.com/whopio/whopsdk-go/v2/internal"
	option "github.com/whopio/whopsdk-go/v2/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.APIVersionDate == nil {
		apiVersionDateDefault := "2026-10-09-2"
		options.APIVersionDate = &apiVersionDateDefault
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Submits an issue or an unanswered question to Whop for review, recorded under the authenticated user, account, or app. Returns a receipt once the submission is accepted; processing is asynchronous and no reply is sent. Accepts user, account, and app credentials.
//
// Example:
//
//	request := &whopsdk.CreateFeedbackSubmissionsRequest{
//	    Content: "The docs omit the required permission",
//	    Source: whopsdk.CreateFeedbackSubmissionsRequestSourceMcpReportFeedback,
//	}
//	client.FeedbackSubmissions.Create(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Create(
	ctx context.Context,
	request *whopsdk.CreateFeedbackSubmissionsRequest,
	opts ...option.RequestOption,
) (*whopsdk.CreateFeedbackSubmissionsResponse, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
