// Code generated by Fern. DO NOT EDIT.

// Swaps convert value between supported tokens, chains, or wallet destinations for an account. A swap quote describes the expected output, fees, and approval requirements before you create the swap.
//
// Use the Swaps API to quote a conversion, create the swap, list recent swaps, and retrieve status until the transaction completes.
package swaps
