// Code generated by Fern. DO NOT EDIT.

package externalaccounts

import (
	json "encoding/json"
	fmt "fmt"
	v2 "github.com/whopio/whopsdk-go/v2"
	internal "github.com/whopio/whopsdk-go/v2/internal"
	big "math/big"
)

var (
	listLeadFormsRequestFieldID        = big.NewInt(1 << 0)
	listLeadFormsRequestFieldAccountID = big.NewInt(1 << 1)
)

type ListLeadFormsRequest struct {
	// The external account (a sacc_ identifier) whose lead forms to list.
	ID string `json:"-" url:"-"`
	// The Account (a biz_ identifier) the external account is connected to.
	AccountID string `json:"-" url:"account_id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListLeadFormsRequest) require(field *big.Int) {
	next := new(big.Int)
	if l.explicitFields != nil {
		next.Set(l.explicitFields)
	}
	next.Or(next, field)
	l.explicitFields = next
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListLeadFormsRequest) SetID(id string) {
	l.ID = id
	l.require(listLeadFormsRequestFieldID)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListLeadFormsRequest) SetAccountID(accountID string) {
	l.AccountID = accountID
	l.require(listLeadFormsRequestFieldAccountID)
}

var (
	listLeadFormsResponseFieldData = big.NewInt(1 << 0)
)

type ListLeadFormsResponse struct {
	Data []*v2.ExternalAccountLeadForm `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListLeadFormsResponse) GetData() []*v2.ExternalAccountLeadForm {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListLeadFormsResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListLeadFormsResponse) require(field *big.Int) {
	next := new(big.Int)
	if l.explicitFields != nil {
		next.Set(l.explicitFields)
	}
	next.Or(next, field)
	l.explicitFields = next
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListLeadFormsResponse) SetData(data []*v2.ExternalAccountLeadForm) {
	l.Data = data
	l.require(listLeadFormsResponseFieldData)
}

func (l *ListLeadFormsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListLeadFormsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListLeadFormsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListLeadFormsResponse) MarshalJSON() ([]byte, error) {
	type embed ListLeadFormsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListLeadFormsResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}
