// Code generated by Fern. DO NOT EDIT.

package externalaccounts

import (
	json "encoding/json"
	fmt "fmt"
	v2 "github.com/whopio/whopsdk-go/v2"
	internal "github.com/whopio/whopsdk-go/v2/internal"
	big "math/big"
)

var (
	createPartnersRequestFieldExternalAccountID = big.NewInt(1 << 0)
	createPartnersRequestFieldAccountID         = big.NewInt(1 << 1)
	createPartnersRequestFieldUsername          = big.NewInt(1 << 2)
)

type CreatePartnersRequest struct {
	// The Instagram account (a sacc_ identifier) the partners run partnership ads with.
	ExternalAccountID string `json:"-" url:"-"`
	// The Account (biz_ identifier) that advertises as the Instagram account. An account-scoped API key may omit this to default to its own account.
	AccountID *string `json:"account_id,omitempty" url:"-"`
	// The creator's Instagram username, with or without the leading `@`. The creator needs a professional (Business or Creator) Instagram account.
	Username string `json:"username" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreatePartnersRequest) require(field *big.Int) {
	next := new(big.Int)
	if c.explicitFields != nil {
		next.Set(c.explicitFields)
	}
	next.Or(next, field)
	c.explicitFields = next
}

// SetExternalAccountID sets the ExternalAccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePartnersRequest) SetExternalAccountID(externalAccountID string) {
	c.ExternalAccountID = externalAccountID
	c.require(createPartnersRequestFieldExternalAccountID)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePartnersRequest) SetAccountID(accountID *string) {
	c.AccountID = accountID
	c.require(createPartnersRequestFieldAccountID)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePartnersRequest) SetUsername(username string) {
	c.Username = username
	c.require(createPartnersRequestFieldUsername)
}

func (c *CreatePartnersRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreatePartnersRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreatePartnersRequest(body)
	return nil
}

func (c *CreatePartnersRequest) MarshalJSON() ([]byte, error) {
	type embed CreatePartnersRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	deletePartnersRequestFieldExternalAccountID = big.NewInt(1 << 0)
	deletePartnersRequestFieldID                = big.NewInt(1 << 1)
	deletePartnersRequestFieldAccountID         = big.NewInt(1 << 2)
)

type DeletePartnersRequest struct {
	// The Instagram account (a sacc_ identifier) the partner runs partnership ads with.
	ExternalAccountID string `json:"-" url:"-"`
	// The partner creator's external account (a sacc_ identifier).
	ID string `json:"-" url:"-"`
	// The Account (biz_ identifier) that advertises as the Instagram account. An account-scoped API key may omit this to default to its own account.
	AccountID *string `json:"-" url:"account_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeletePartnersRequest) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetExternalAccountID sets the ExternalAccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeletePartnersRequest) SetExternalAccountID(externalAccountID string) {
	d.ExternalAccountID = externalAccountID
	d.require(deletePartnersRequestFieldExternalAccountID)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeletePartnersRequest) SetID(id string) {
	d.ID = id
	d.require(deletePartnersRequestFieldID)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeletePartnersRequest) SetAccountID(accountID *string) {
	d.AccountID = accountID
	d.require(deletePartnersRequestFieldAccountID)
}

var (
	listPartnersRequestFieldExternalAccountID = big.NewInt(1 << 0)
	listPartnersRequestFieldAccountID         = big.NewInt(1 << 1)
	listPartnersRequestFieldFirst             = big.NewInt(1 << 2)
	listPartnersRequestFieldAfter             = big.NewInt(1 << 3)
)

type ListPartnersRequest struct {
	// The Instagram account (a sacc_ identifier) the partners run partnership ads with.
	ExternalAccountID string `json:"-" url:"-"`
	// The Account (biz_ identifier) that advertises as the Instagram account. An account-scoped API key may omit this to default to its own account.
	AccountID *string `json:"-" url:"account_id,omitempty"`
	// Number of results to return from the start of the range.
	First *int `json:"-" url:"first,omitempty"`
	// Return results after this cursor. Use `page_info.end_cursor` from the previous response to fetch the next page.
	After *string `json:"-" url:"after,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListPartnersRequest) require(field *big.Int) {
	next := new(big.Int)
	if l.explicitFields != nil {
		next.Set(l.explicitFields)
	}
	next.Or(next, field)
	l.explicitFields = next
}

// SetExternalAccountID sets the ExternalAccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPartnersRequest) SetExternalAccountID(externalAccountID string) {
	l.ExternalAccountID = externalAccountID
	l.require(listPartnersRequestFieldExternalAccountID)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPartnersRequest) SetAccountID(accountID *string) {
	l.AccountID = accountID
	l.require(listPartnersRequestFieldAccountID)
}

// SetFirst sets the First field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPartnersRequest) SetFirst(first *int) {
	l.First = first
	l.require(listPartnersRequestFieldFirst)
}

// SetAfter sets the After field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPartnersRequest) SetAfter(after *string) {
	l.After = after
	l.require(listPartnersRequestFieldAfter)
}

var (
	deletePartnersResponseFieldDeleted = big.NewInt(1 << 0)
	deletePartnersResponseFieldID      = big.NewInt(1 << 1)
)

type DeletePartnersResponse struct {
	// Always true.
	Deleted bool `json:"deleted" url:"deleted"`
	// ID of the removed partner's external account.
	ID string `json:"id" url:"id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeletePartnersResponse) GetDeleted() bool {
	if d == nil {
		return false
	}
	return d.Deleted
}

func (d *DeletePartnersResponse) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DeletePartnersResponse) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeletePartnersResponse) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetDeleted sets the Deleted field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeletePartnersResponse) SetDeleted(deleted bool) {
	d.Deleted = deleted
	d.require(deletePartnersResponseFieldDeleted)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeletePartnersResponse) SetID(id string) {
	d.ID = id
	d.require(deletePartnersResponseFieldID)
}

func (d *DeletePartnersResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DeletePartnersResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeletePartnersResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeletePartnersResponse) MarshalJSON() ([]byte, error) {
	type embed DeletePartnersResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeletePartnersResponse) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	listPartnersResponseFieldData     = big.NewInt(1 << 0)
	listPartnersResponseFieldPageInfo = big.NewInt(1 << 1)
)

type ListPartnersResponse struct {
	Data     []*v2.ExternalAccount         `json:"data" url:"data"`
	PageInfo *ListPartnersResponsePageInfo `json:"page_info" url:"page_info"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListPartnersResponse) GetData() []*v2.ExternalAccount {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListPartnersResponse) GetPageInfo() *ListPartnersResponsePageInfo {
	if l == nil {
		return nil
	}
	return l.PageInfo
}

func (l *ListPartnersResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListPartnersResponse) require(field *big.Int) {
	next := new(big.Int)
	if l.explicitFields != nil {
		next.Set(l.explicitFields)
	}
	next.Or(next, field)
	l.explicitFields = next
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPartnersResponse) SetData(data []*v2.ExternalAccount) {
	l.Data = data
	l.require(listPartnersResponseFieldData)
}

// SetPageInfo sets the PageInfo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPartnersResponse) SetPageInfo(pageInfo *ListPartnersResponsePageInfo) {
	l.PageInfo = pageInfo
	l.require(listPartnersResponseFieldPageInfo)
}

func (l *ListPartnersResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListPartnersResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListPartnersResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListPartnersResponse) MarshalJSON() ([]byte, error) {
	type embed ListPartnersResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListPartnersResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	listPartnersResponsePageInfoFieldEndCursor       = big.NewInt(1 << 0)
	listPartnersResponsePageInfoFieldHasNextPage     = big.NewInt(1 << 1)
	listPartnersResponsePageInfoFieldHasPreviousPage = big.NewInt(1 << 2)
	listPartnersResponsePageInfoFieldStartCursor     = big.NewInt(1 << 3)
)

// listPartnersResponsePageInfoNullableFields maps the wire names of ListPartnersResponsePageInfo's nullable fields (required or optional) to their field bits.
var listPartnersResponsePageInfoNullableFields = map[string]*big.Int{
	"end_cursor":   listPartnersResponsePageInfoFieldEndCursor,
	"start_cursor": listPartnersResponsePageInfoFieldStartCursor,
}

type ListPartnersResponsePageInfo struct {
	EndCursor       *string `json:"end_cursor,omitempty" url:"end_cursor,omitempty"`
	HasNextPage     bool    `json:"has_next_page" url:"has_next_page"`
	HasPreviousPage bool    `json:"has_previous_page" url:"has_previous_page"`
	StartCursor     *string `json:"start_cursor,omitempty" url:"start_cursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListPartnersResponsePageInfo) GetEndCursor() *string {
	if l == nil {
		return nil
	}
	return l.EndCursor
}

func (l *ListPartnersResponsePageInfo) GetHasNextPage() bool {
	if l == nil {
		return false
	}
	return l.HasNextPage
}

func (l *ListPartnersResponsePageInfo) GetHasPreviousPage() bool {
	if l == nil {
		return false
	}
	return l.HasPreviousPage
}

func (l *ListPartnersResponsePageInfo) GetStartCursor() *string {
	if l == nil {
		return nil
	}
	return l.StartCursor
}

func (l *ListPartnersResponsePageInfo) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListPartnersResponsePageInfo) require(field *big.Int) {
	next := new(big.Int)
	if l.explicitFields != nil {
		next.Set(l.explicitFields)
	}
	next.Or(next, field)
	l.explicitFields = next
}

// SetEndCursor sets the EndCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPartnersResponsePageInfo) SetEndCursor(endCursor *string) {
	l.EndCursor = endCursor
	l.require(listPartnersResponsePageInfoFieldEndCursor)
}

// SetHasNextPage sets the HasNextPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPartnersResponsePageInfo) SetHasNextPage(hasNextPage bool) {
	l.HasNextPage = hasNextPage
	l.require(listPartnersResponsePageInfoFieldHasNextPage)
}

// SetHasPreviousPage sets the HasPreviousPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPartnersResponsePageInfo) SetHasPreviousPage(hasPreviousPage bool) {
	l.HasPreviousPage = hasPreviousPage
	l.require(listPartnersResponsePageInfoFieldHasPreviousPage)
}

// SetStartCursor sets the StartCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPartnersResponsePageInfo) SetStartCursor(startCursor *string) {
	l.StartCursor = startCursor
	l.require(listPartnersResponsePageInfoFieldStartCursor)
}

func (l *ListPartnersResponsePageInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler ListPartnersResponsePageInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListPartnersResponsePageInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	presentFields, err := internal.ExplicitFieldsFromJSON(data, listPartnersResponsePageInfoNullableFields)
	if err != nil {
		return err
	}
	if presentFields != nil {
		l.require(presentFields)
	}
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListPartnersResponsePageInfo) MarshalJSON() ([]byte, error) {
	type embed ListPartnersResponsePageInfo
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListPartnersResponsePageInfo) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}
