// Code generated by Fern. DO NOT EDIT.

package preferences

import (
	json "encoding/json"
	fmt "fmt"
	whopsdkgo "github.com/whopio/whopsdk-go"
	internal "github.com/whopio/whopsdk-go/internal"
	big "math/big"
)

var (
	setNotificationsRequestFieldPreferences = big.NewInt(1 << 0)
)

type SetNotificationsRequest struct {
	// The preferences to set, at most 100 per request.
	Preferences []*SetNotificationsRequestPreferencesItem `json:"preferences" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SetNotificationsRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetPreferences sets the Preferences field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SetNotificationsRequest) SetPreferences(preferences []*SetNotificationsRequestPreferencesItem) {
	s.Preferences = preferences
	s.require(setNotificationsRequestFieldPreferences)
}

func (s *SetNotificationsRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler SetNotificationsRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*s = SetNotificationsRequest(body)
	return nil
}

func (s *SetNotificationsRequest) MarshalJSON() ([]byte, error) {
	type embed SetNotificationsRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	setNotificationsRequestPreferencesItemFieldLevel = big.NewInt(1 << 0)
	setNotificationsRequestPreferencesItemFieldScope = big.NewInt(1 << 1)
)

type SetNotificationsRequestPreferencesItem struct {
	// What the user is notified about in this scope. `mentions` is only valid for an experience level. `null` clears the preference.
	Level *SetNotificationsRequestPreferencesItemLevel `json:"level,omitempty" url:"level,omitempty"`
	// What the preference applies to. `null` on a dimension means the preference is not narrowed there.
	Scope *SetNotificationsRequestPreferencesItemScope `json:"scope" url:"scope"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SetNotificationsRequestPreferencesItem) GetLevel() *SetNotificationsRequestPreferencesItemLevel {
	if s == nil {
		return nil
	}
	return s.Level
}

func (s *SetNotificationsRequestPreferencesItem) GetScope() *SetNotificationsRequestPreferencesItemScope {
	if s == nil {
		return nil
	}
	return s.Scope
}

func (s *SetNotificationsRequestPreferencesItem) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SetNotificationsRequestPreferencesItem) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetLevel sets the Level field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SetNotificationsRequestPreferencesItem) SetLevel(level *SetNotificationsRequestPreferencesItemLevel) {
	s.Level = level
	s.require(setNotificationsRequestPreferencesItemFieldLevel)
}

// SetScope sets the Scope field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SetNotificationsRequestPreferencesItem) SetScope(scope *SetNotificationsRequestPreferencesItemScope) {
	s.Scope = scope
	s.require(setNotificationsRequestPreferencesItemFieldScope)
}

func (s *SetNotificationsRequestPreferencesItem) UnmarshalJSON(data []byte) error {
	type unmarshaler SetNotificationsRequestPreferencesItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SetNotificationsRequestPreferencesItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SetNotificationsRequestPreferencesItem) MarshalJSON() ([]byte, error) {
	type embed SetNotificationsRequestPreferencesItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SetNotificationsRequestPreferencesItem) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

// What the user is notified about in this scope. `mentions` is only valid for an experience level. `null` clears the preference.
type SetNotificationsRequestPreferencesItemLevel string

const (
	SetNotificationsRequestPreferencesItemLevelAll      SetNotificationsRequestPreferencesItemLevel = "all"
	SetNotificationsRequestPreferencesItemLevelMentions SetNotificationsRequestPreferencesItemLevel = "mentions"
	SetNotificationsRequestPreferencesItemLevelNothing  SetNotificationsRequestPreferencesItemLevel = "nothing"
)

func NewSetNotificationsRequestPreferencesItemLevelFromString(s string) (SetNotificationsRequestPreferencesItemLevel, error) {
	switch s {
	case "all":
		return SetNotificationsRequestPreferencesItemLevelAll, nil
	case "mentions":
		return SetNotificationsRequestPreferencesItemLevelMentions, nil
	case "nothing":
		return SetNotificationsRequestPreferencesItemLevelNothing, nil
	}
	var t SetNotificationsRequestPreferencesItemLevel
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SetNotificationsRequestPreferencesItemLevel) Ptr() *SetNotificationsRequestPreferencesItemLevel {
	return &s
}

// What the preference applies to. `null` on a dimension means the preference is not narrowed there.
var (
	setNotificationsRequestPreferencesItemScopeFieldAccountID     = big.NewInt(1 << 0)
	setNotificationsRequestPreferencesItemScopeFieldChannel       = big.NewInt(1 << 1)
	setNotificationsRequestPreferencesItemScopeFieldExperienceID  = big.NewInt(1 << 2)
	setNotificationsRequestPreferencesItemScopeFieldTeamAccountID = big.NewInt(1 << 3)
	setNotificationsRequestPreferencesItemScopeFieldTopicID       = big.NewInt(1 << 4)
)

type SetNotificationsRequestPreferencesItemScope struct {
	// Account to scope the preference to (member notifications), `biz_` tag.
	AccountID *string `json:"account_id,omitempty" url:"account_id,omitempty"`
	// Delivery channel the preference applies to. Required when setting a topic override.
	Channel *SetNotificationsRequestPreferencesItemScopeChannel `json:"channel,omitempty" url:"channel,omitempty"`
	// Experience to scope the preference to (`exp_` tag). Requires `account_id` when a `topic_id` is also given.
	ExperienceID *string `json:"experience_id,omitempty" url:"experience_id,omitempty"`
	// Account whose team notifications the preference is scoped to, `biz_` tag.
	TeamAccountID *string `json:"team_account_id,omitempty" url:"team_account_id,omitempty"`
	// Notification topic to scope the preference to, `topic_` tag.
	TopicID *string `json:"topic_id,omitempty" url:"topic_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SetNotificationsRequestPreferencesItemScope) GetAccountID() *string {
	if s == nil {
		return nil
	}
	return s.AccountID
}

func (s *SetNotificationsRequestPreferencesItemScope) GetChannel() *SetNotificationsRequestPreferencesItemScopeChannel {
	if s == nil {
		return nil
	}
	return s.Channel
}

func (s *SetNotificationsRequestPreferencesItemScope) GetExperienceID() *string {
	if s == nil {
		return nil
	}
	return s.ExperienceID
}

func (s *SetNotificationsRequestPreferencesItemScope) GetTeamAccountID() *string {
	if s == nil {
		return nil
	}
	return s.TeamAccountID
}

func (s *SetNotificationsRequestPreferencesItemScope) GetTopicID() *string {
	if s == nil {
		return nil
	}
	return s.TopicID
}

func (s *SetNotificationsRequestPreferencesItemScope) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SetNotificationsRequestPreferencesItemScope) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SetNotificationsRequestPreferencesItemScope) SetAccountID(accountID *string) {
	s.AccountID = accountID
	s.require(setNotificationsRequestPreferencesItemScopeFieldAccountID)
}

// SetChannel sets the Channel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SetNotificationsRequestPreferencesItemScope) SetChannel(channel *SetNotificationsRequestPreferencesItemScopeChannel) {
	s.Channel = channel
	s.require(setNotificationsRequestPreferencesItemScopeFieldChannel)
}

// SetExperienceID sets the ExperienceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SetNotificationsRequestPreferencesItemScope) SetExperienceID(experienceID *string) {
	s.ExperienceID = experienceID
	s.require(setNotificationsRequestPreferencesItemScopeFieldExperienceID)
}

// SetTeamAccountID sets the TeamAccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SetNotificationsRequestPreferencesItemScope) SetTeamAccountID(teamAccountID *string) {
	s.TeamAccountID = teamAccountID
	s.require(setNotificationsRequestPreferencesItemScopeFieldTeamAccountID)
}

// SetTopicID sets the TopicID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SetNotificationsRequestPreferencesItemScope) SetTopicID(topicID *string) {
	s.TopicID = topicID
	s.require(setNotificationsRequestPreferencesItemScopeFieldTopicID)
}

func (s *SetNotificationsRequestPreferencesItemScope) UnmarshalJSON(data []byte) error {
	type unmarshaler SetNotificationsRequestPreferencesItemScope
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SetNotificationsRequestPreferencesItemScope(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SetNotificationsRequestPreferencesItemScope) MarshalJSON() ([]byte, error) {
	type embed SetNotificationsRequestPreferencesItemScope
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SetNotificationsRequestPreferencesItemScope) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

// Delivery channel the preference applies to. Required when setting a topic override.
type SetNotificationsRequestPreferencesItemScopeChannel string

const (
	SetNotificationsRequestPreferencesItemScopeChannelInApp  SetNotificationsRequestPreferencesItemScopeChannel = "in_app"
	SetNotificationsRequestPreferencesItemScopeChannelMobile SetNotificationsRequestPreferencesItemScopeChannel = "mobile"
)

func NewSetNotificationsRequestPreferencesItemScopeChannelFromString(s string) (SetNotificationsRequestPreferencesItemScopeChannel, error) {
	switch s {
	case "in_app":
		return SetNotificationsRequestPreferencesItemScopeChannelInApp, nil
	case "mobile":
		return SetNotificationsRequestPreferencesItemScopeChannelMobile, nil
	}
	var t SetNotificationsRequestPreferencesItemScopeChannel
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SetNotificationsRequestPreferencesItemScopeChannel) Ptr() *SetNotificationsRequestPreferencesItemScopeChannel {
	return &s
}

var (
	setNotificationsResponseFieldData = big.NewInt(1 << 0)
)

type SetNotificationsResponse struct {
	Data []*whopsdkgo.NotificationPreferenceState `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SetNotificationsResponse) GetData() []*whopsdkgo.NotificationPreferenceState {
	if s == nil {
		return nil
	}
	return s.Data
}

func (s *SetNotificationsResponse) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SetNotificationsResponse) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SetNotificationsResponse) SetData(data []*whopsdkgo.NotificationPreferenceState) {
	s.Data = data
	s.require(setNotificationsResponseFieldData)
}

func (s *SetNotificationsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler SetNotificationsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SetNotificationsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SetNotificationsResponse) MarshalJSON() ([]byte, error) {
	type embed SetNotificationsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SetNotificationsResponse) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}
