// Code generated by Fern. DO NOT EDIT.

package checkoutconfigurations

import (
	context "context"
	http "net/http"

	whopsdk "github.com/whopio/whopsdk-go"
	core "github.com/whopio/whopsdk-go/core"
	internal "github.com/whopio/whopsdk-go/internal"
	option "github.com/whopio/whopsdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.APIVersionDate == nil {
		apiVersionDateDefault := "2026-08-25-1"
		options.APIVersionDate = &apiVersionDateDefault
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Lists checkout configurations for an account.
//
// Example:
//
//	request := &whopsdk.ListCheckoutConfigurationsRequest{
//	    AccountID: "account_id",
//	}
//	client.CheckoutConfigurations.List(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) List(
	ctx context.Context,
	request *whopsdk.ListCheckoutConfigurationsRequest,
	opts ...option.RequestOption,
) (*core.Page[*string, *whopsdk.ListCheckoutConfigurationsResponseDataItem, *whopsdk.ListCheckoutConfigurationsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://api.whop.com/api/v1",
	)
	endpointURL := baseURL + "/checkout_configurations"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	prepareCall := func(pageRequest *core.PageRequest[*string]) *internal.CallParams {
		if pageRequest.Cursor != nil {
			queryParams.Set("after", *pageRequest.Cursor)
		}
		nextURL := endpointURL
		if len(queryParams) > 0 {
			nextURL += "?" + queryParams.Encode()
		}
		return &internal.CallParams{
			URL:             nextURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        pageRequest.Response,
			ErrorDecoder:    internal.NewErrorDecoder(whopsdk.ErrorCodes),
		}
	}
	readPageResponse := func(response *whopsdk.ListCheckoutConfigurationsResponse) *core.PageResponse[*string, *whopsdk.ListCheckoutConfigurationsResponseDataItem, *whopsdk.ListCheckoutConfigurationsResponse] {
		var zeroValue *string
		var next *string
		if response.PageInfo != nil {
			next = response.PageInfo.EndCursor
		}
		results := response.GetData()
		return &core.PageResponse[*string, *whopsdk.ListCheckoutConfigurationsResponseDataItem, *whopsdk.ListCheckoutConfigurationsResponse]{
			Results:  results,
			Response: response,
			Next:     next,
			Done:     next == zeroValue || *next == "",
		}
	}
	pager := internal.NewCursorPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, request.After)
}

// Creates a reusable checkout configuration for an existing or inline plan.
//
// Example:
//
//	request := &whopsdk.CreateCheckoutConfigurationsRequest{
//	    AccountID: whopsdk.String(
//	        "biz_xxxxxxxxxxxxxx",
//	    ),
//	    PlanID: whopsdk.String(
//	        "plan_xxxxxxxxxxxxx",
//	    ),
//	}
//	client.CheckoutConfigurations.Create(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Create(
	ctx context.Context,
	request *whopsdk.CreateCheckoutConfigurationsRequest,
	opts ...option.RequestOption,
) (*whopsdk.CreateCheckoutConfigurationsResponse, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieves a checkout configuration by ID. This endpoint is public so a checkout page can load from the configuration URL.
//
// Example:
//
//	request := &whopsdk.RetrieveCheckoutConfigurationsRequest{
//	    ID: "id",
//	}
//	client.CheckoutConfigurations.Retrieve(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Retrieve(
	ctx context.Context,
	request *whopsdk.RetrieveCheckoutConfigurationsRequest,
	opts ...option.RequestOption,
) (*whopsdk.RetrieveCheckoutConfigurationsResponse, error) {
	response, err := c.WithRawResponse.Retrieve(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Deletes a checkout configuration so its checkout URL can no longer be used.
//
// Example:
//
//	request := &whopsdk.DeleteCheckoutConfigurationsRequest{
//	    ID: "id",
//	}
//	client.CheckoutConfigurations.Delete(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Delete(
	ctx context.Context,
	request *whopsdk.DeleteCheckoutConfigurationsRequest,
	opts ...option.RequestOption,
) (*whopsdk.DeleteCheckoutConfigurationsResponse, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
