// Code generated by Fern. DO NOT EDIT.

package domains

import (
	context "context"
	http "net/http"

	whopsdk "github.com/whopio/whopsdk-go"
	core "github.com/whopio/whopsdk-go/core"
	internal "github.com/whopio/whopsdk-go/internal"
	option "github.com/whopio/whopsdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.APIVersionDate == nil {
		apiVersionDateDefault := "2026-09-09"
		options.APIVersionDate = &apiVersionDateDefault
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Lists the caller's domain claims and assignments. Filter by account, app, or lifecycle status.
//
// Example:
//
//	request := &whopsdk.ListDomainsRequest{}
//	client.Domains.List(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) List(
	ctx context.Context,
	request *whopsdk.ListDomainsRequest,
	opts ...option.RequestOption,
) (*core.Page[*string, *whopsdk.Domain, *whopsdk.ListDomainsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://api.whop.com/api/v1",
	)
	endpointURL := baseURL + "/domains"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	prepareCall := func(pageRequest *core.PageRequest[*string]) *internal.CallParams {
		if pageRequest.Cursor != nil {
			queryParams.Set("after", *pageRequest.Cursor)
		}
		nextURL := endpointURL
		if len(queryParams) > 0 {
			nextURL += "?" + queryParams.Encode()
		}
		return &internal.CallParams{
			URL:             nextURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        pageRequest.Response,
		}
	}
	readPageResponse := func(response *whopsdk.ListDomainsResponse) *core.PageResponse[*string, *whopsdk.Domain, *whopsdk.ListDomainsResponse] {
		var zeroValue *string
		var next *string
		if response.PageInfo != nil {
			next = response.PageInfo.EndCursor
		}
		results := response.GetData()
		return &core.PageResponse[*string, *whopsdk.Domain, *whopsdk.ListDomainsResponse]{
			Results:  results,
			Response: response,
			Next:     next,
			Done:     next == zeroValue || *next == "",
		}
	}
	pager := internal.NewCursorPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, request.After)
}

// Creates an unverified claim and returns DNS instructions. A claim does not reserve the hostname globally. Publish its unique TXT record; ownership verification, DNS checks, and certificate provisioning run automatically. Unverified claims are deleted after 48 hours.
//
// Example:
//
//	request := &whopsdk.CreateDomainsRequest{
//	    AppID: "app_xxxxxxxxxxxxxx",
//	    Domain: "store.example.com",
//	}
//	client.Domains.Create(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Create(
	ctx context.Context,
	request *whopsdk.CreateDomainsRequest,
	opts ...option.RequestOption,
) (*whopsdk.Domain, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieves the claim, app assignment, DNS instructions, and the latest hostname and certificate state. For domains still connecting, needing attention, or being deleted, requests an immediate background check.
//
// Example:
//
//	request := &whopsdk.RetrieveDomainsRequest{
//	    ID: "id",
//	}
//	client.Domains.Retrieve(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Retrieve(
	ctx context.Context,
	request *whopsdk.RetrieveDomainsRequest,
	opts ...option.RequestOption,
) (*whopsdk.Domain, error) {
	response, err := c.WithRawResponse.Retrieve(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Stops resolving the domain to its app and queues Cloudflare cleanup. The response is deleting; retrieve the resource until it is removed.
//
// Example:
//
//	request := &whopsdk.DeleteDomainsRequest{
//	    ID: "id",
//	}
//	client.Domains.Delete(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Delete(
	ctx context.Context,
	request *whopsdk.DeleteDomainsRequest,
	opts ...option.RequestOption,
) (*whopsdk.Domain, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Reassigns a domain to another app in the same account or replaces its metadata. The hostname and owning account cannot be edited.
//
// Example:
//
//	request := &whopsdk.UpdateDomainsRequest{
//	    ID: "id",
//	}
//	client.Domains.Update(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Update(
	ctx context.Context,
	request *whopsdk.UpdateDomainsRequest,
	opts ...option.RequestOption,
) (*whopsdk.Domain, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
