// Code generated by Fern. DO NOT EDIT.

package adcampaigns

import (
	context "context"
	http "net/http"

	whopsdk "github.com/whopio/whopsdk-go"
	core "github.com/whopio/whopsdk-go/core"
	internal "github.com/whopio/whopsdk-go/internal"
	option "github.com/whopio/whopsdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.APIVersionDate == nil {
		apiVersionDateDefault := "2026-08-25-2"
		options.APIVersionDate = &apiVersionDateDefault
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Lists the ad campaigns for an account, with stats over the requested window.
//
// Example:
//
//	request := &whopsdk.ListAdCampaignsRequest{}
//	client.AdCampaigns.List(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) List(
	ctx context.Context,
	request *whopsdk.ListAdCampaignsRequest,
	opts ...option.RequestOption,
) (*core.Page[*string, *whopsdk.AdCampaign, *whopsdk.ListAdCampaignsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://api.whop.com/api/v1",
	)
	endpointURL := baseURL + "/ad_campaigns"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	prepareCall := func(pageRequest *core.PageRequest[*string]) *internal.CallParams {
		if pageRequest.Cursor != nil {
			queryParams.Set("after", *pageRequest.Cursor)
		}
		nextURL := endpointURL
		if len(queryParams) > 0 {
			nextURL += "?" + queryParams.Encode()
		}
		return &internal.CallParams{
			URL:             nextURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        pageRequest.Response,
			ErrorDecoder:    internal.NewErrorDecoder(whopsdk.ErrorCodes),
		}
	}
	readPageResponse := func(response *whopsdk.ListAdCampaignsResponse) *core.PageResponse[*string, *whopsdk.AdCampaign, *whopsdk.ListAdCampaignsResponse] {
		var zeroValue *string
		var next *string
		if response.PageInfo != nil {
			next = response.PageInfo.EndCursor
		}
		results := response.GetData()
		return &core.PageResponse[*string, *whopsdk.AdCampaign, *whopsdk.ListAdCampaignsResponse]{
			Results:  results,
			Response: response,
			Next:     next,
			Done:     next == zeroValue || *next == "",
		}
	}
	pager := internal.NewCursorPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, request.After)
}

// Creates an ad campaign for an account.
//
// Example:
//
//	request := &whopsdk.CreateAdCampaignsRequest{
//	    Objective: whopsdk.CreateAdCampaignsRequestObjectiveAwareness,
//	    Platform: whopsdk.CreateAdCampaignsRequestPlatformMeta,
//	    Title: "Now hiring mobile detailers — Austin",
//	}
//	client.AdCampaigns.Create(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Create(
	ctx context.Context,
	request *whopsdk.CreateAdCampaignsRequest,
	opts ...option.RequestOption,
) (*whopsdk.AdCampaign, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieves a single ad campaign with stats over the requested window.
//
// Example:
//
//	request := &whopsdk.RetrieveAdCampaignsRequest{
//	    ID: "id",
//	}
//	client.AdCampaigns.Retrieve(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Retrieve(
	ctx context.Context,
	request *whopsdk.RetrieveAdCampaignsRequest,
	opts ...option.RequestOption,
) (*whopsdk.AdCampaign, error) {
	response, err := c.WithRawResponse.Retrieve(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Deletes an ad campaign and archives it on the ad platform (cascades to ad groups and ads).
//
// Example:
//
//	request := &whopsdk.DeleteAdCampaignsRequest{
//	    ID: "id",
//	}
//	client.AdCampaigns.Delete(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Delete(
	ctx context.Context,
	request *whopsdk.DeleteAdCampaignsRequest,
	opts ...option.RequestOption,
) (*whopsdk.DeleteAdCampaignsResponse, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Updates an ad campaign's editable fields (title, budget, schedule, bid strategy, special ad categories, and, before launch, budget type and budget optimization), and launches a draft campaign by setting status to active. Objective and desired cost per result are fixed at creation and cannot be changed.
//
// Example:
//
//	request := &whopsdk.UpdateAdCampaignsRequest{
//	    ID: "id",
//	}
//	client.AdCampaigns.Update(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Update(
	ctx context.Context,
	request *whopsdk.UpdateAdCampaignsRequest,
	opts ...option.RequestOption,
) (*whopsdk.AdCampaign, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Creates copies of the campaign in `duplicating` status and returns them; each copy transitions to `draft` once duplication completes. Poll each returned campaign until it leaves `duplicating` — a copy that could not be completed is deleted and returns 404.
//
// Example:
//
//	request := &whopsdk.DuplicateAdCampaignsRequest{
//	    ID: "id",
//	}
//	client.AdCampaigns.Duplicate(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Duplicate(
	ctx context.Context,
	request *whopsdk.DuplicateAdCampaignsRequest,
	opts ...option.RequestOption,
) (*whopsdk.DuplicateAdCampaignsResponse, error) {
	response, err := c.WithRawResponse.Duplicate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Pauses an active ad campaign.
//
// Example:
//
//	request := &whopsdk.PauseAdCampaignsRequest{
//	    ID: "id",
//	}
//	client.AdCampaigns.Pause(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Pause(
	ctx context.Context,
	request *whopsdk.PauseAdCampaignsRequest,
	opts ...option.RequestOption,
) (*whopsdk.AdCampaign, error) {
	response, err := c.WithRawResponse.Pause(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retries billing for an ad campaign whose payment previously failed.
//
// Example:
//
//	request := &whopsdk.RetryPaymentAdCampaignsRequest{
//	    ID: "id",
//	}
//	client.AdCampaigns.RetryPayment(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) RetryPayment(
	ctx context.Context,
	request *whopsdk.RetryPaymentAdCampaignsRequest,
	opts ...option.RequestOption,
) (*whopsdk.AdCampaign, error) {
	response, err := c.WithRawResponse.RetryPayment(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Resumes a paused ad campaign.
//
// Example:
//
//	request := &whopsdk.UnpauseAdCampaignsRequest{
//	    ID: "id",
//	}
//	client.AdCampaigns.Unpause(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Unpause(
	ctx context.Context,
	request *whopsdk.UnpauseAdCampaignsRequest,
	opts ...option.RequestOption,
) (*whopsdk.AdCampaign, error) {
	response, err := c.WithRawResponse.Unpause(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
